--------------------------------------------------------
--  DDL for Table T_FUNCTIONS
--------------------------------------------------------
  CREATE TABLE "DGS_ICDM"."T_FUNCTIONS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"LONGNAME" VARCHAR2(255 BYTE), 
	"ISCUSTFUNC" VARCHAR2(1 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(100 BYTE), 
	"MODIFED_DATE" TIMESTAMP (6), 
	"MODIFED_USER" VARCHAR2(100 BYTE), 
	"VERSION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS" ;

--------------------------------------------------------
--  DDL for Table T_FUNCTIONVERSIONS
--------------------------------------------------------
  CREATE TABLE "DGS_ICDM"."T_FUNCTIONVERSIONS" 
   (	"ID" NUMBER, 
	"FUNCNAME" VARCHAR2(255 BYTE), 
	"FUNCVERSION" VARCHAR2(255 BYTE), 
	"DEFCHARNAME" VARCHAR2(255 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS" ;

--------------------------------------------------------
--  DDL for Table T_PARAMETER
--------------------------------------------------------
  CREATE TABLE "DGS_ICDM"."T_PARAMETER" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"LONGNAME" VARCHAR2(1024 BYTE), 
	"PTYPE" VARCHAR2(31 BYTE), 
	"PCLASS" VARCHAR2(1 BYTE), 
	"ISCODEWORD" VARCHAR2(1 BYTE), 
	"ISCUSTPRM" VARCHAR2(1 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(100 BYTE), 
	"MODIFED_DATE" TIMESTAMP (6), 
	"MODIFED_USER" VARCHAR2(100 BYTE), 
	"VERSION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS" ;

--------------------------------------------------------
--  DDL for Table T_UNITS
--------------------------------------------------------
CREATE TABLE "DGS_ICDM"."T_UNITS"
  (
    UNIT VARCHAR2 (255 BYTE) NOT NULL,
	CREATED_DATE TIMESTAMP (6), 
	VERSION NUMBER NOT NULL
  )
;

CREATE UNIQUE INDEX "DGS_ICDM"."PK_UNITS" ON "DGS_ICDM"."T_UNITS"
  (
    UNIT ASC
  )
;

ALTER TABLE "DGS_ICDM"."T_UNITS"
  ADD CONSTRAINT PK_UNITS PRIMARY KEY ( UNIT ) USING INDEX "DGS_ICDM"."PK_UNITS" 
;
  
--------------------------------------------------------
--  DDL for Index PK_FUNCTIONS
--------------------------------------------------------
  CREATE UNIQUE INDEX "DGS_ICDM"."PK_FUNCTIONS" ON "DGS_ICDM"."T_FUNCTIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS" ;
  
--------------------------------------------------------
--  DDL for Index UK_FUNC_NAME
--------------------------------------------------------
  CREATE UNIQUE INDEX "DGS_ICDM"."UK_FUNC_NAME" ON "DGS_ICDM"."T_FUNCTIONS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS" ;
  
--------------------------------------------------------
--  DDL for Index PK_FUNCVERS
--------------------------------------------------------
  CREATE UNIQUE INDEX "DGS_ICDM"."PK_FUNCVERS" ON "DGS_ICDM"."T_FUNCTIONVERSIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS" ;
  
--------------------------------------------------------
--  DDL for Index UK_FUNCVERS
--------------------------------------------------------
  CREATE UNIQUE INDEX "DGS_ICDM"."UK_FUNCVERS" ON "DGS_ICDM"."T_FUNCTIONVERSIONS" ("FUNCNAME", "FUNCVERSION", "DEFCHARNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS" ;
  
--------------------------------------------------------
--  DDL for Index PK_PARAMETER
--------------------------------------------------------
  CREATE UNIQUE INDEX "DGS_ICDM"."PK_PARAMETER" ON "DGS_ICDM"."T_PARAMETER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS" ;
  
--------------------------------------------------------
--  DDL for Index UK_PARAMETER
--------------------------------------------------------
  CREATE UNIQUE INDEX "DGS_ICDM"."UK_PARAMETER" ON "DGS_ICDM"."T_PARAMETER" ("NAME", "PTYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS" ;
  
--------------------------------------------------------
--  Constraints for Table T_FUNCTIONS
--------------------------------------------------------
  ALTER TABLE "DGS_ICDM"."T_FUNCTIONS" ADD CONSTRAINT "PK_FUNCTIONS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS"  ENABLE;
  ALTER TABLE "DGS_ICDM"."T_FUNCTIONS" ADD CONSTRAINT "UK_FUNC_NAME" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS"  ENABLE;
  
--------------------------------------------------------
--  Constraints for Table T_FUNCTIONVERSIONS
--------------------------------------------------------
  ALTER TABLE "DGS_ICDM"."T_FUNCTIONVERSIONS" ADD CONSTRAINT "PK_FUNCVERS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS"  ENABLE;
  ALTER TABLE "DGS_ICDM"."T_FUNCTIONVERSIONS" MODIFY ("FUNCNAME" NOT NULL ENABLE);
  
--------------------------------------------------------
--  Constraints for Table T_PARAMETER
--------------------------------------------------------
  ALTER TABLE "DGS_ICDM"."T_PARAMETER" ADD CONSTRAINT "UK_PARAMETER" UNIQUE ("NAME", "PTYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS"  ENABLE;
  ALTER TABLE "DGS_ICDM"."T_PARAMETER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DGS_ICDM"."T_PARAMETER" ADD CONSTRAINT "PK_PARAMETER" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS"  ENABLE;
  
--------------------------------------------------------
--  Ref Constraints for Table T_FUNCTIONVERSIONS
--------------------------------------------------------
  ALTER TABLE "DGS_ICDM"."T_FUNCTIONVERSIONS" ADD CONSTRAINT "FK_FUNCVERS_FUNC" FOREIGN KEY ("FUNCNAME")
	  REFERENCES "DGS_ICDM"."T_FUNCTIONS" ("NAME") ENABLE;
	  
