spool c:\temp\synonyms.log

--------------------------------------------------------
--  August-02-2013  
--------------------------------------------------------

CREATE OR REPLACE SYNONYM TABV_ICDM_FILES FOR DGS_ICDM.TABV_ICDM_FILES;
CREATE OR REPLACE SYNONYM TABV_ICDM_FILE_DATA FOR DGS_ICDM.TABV_ICDM_FILE_DATA;

---- iCDM-471 ---
CREATE OR REPLACE SYNONYM T_FUNCTIONS FOR DGS_ICDM.T_FUNCTIONS;
CREATE OR REPLACE SYNONYM T_FUNCTIONVERSIONS FOR DGS_ICDM.T_FUNCTIONVERSIONS;
CREATE OR REPLACE SYNONYM T_PARAMETER FOR DGS_ICDM.T_PARAMETER;
CREATE OR REPLACE SYNONYM T_UNITS FOR DGS_ICDM.T_UNITS;

---- ICDM-497 ---
CREATE OR REPLACE SYNONYM T_REVIEW_RULES FOR DGS_ICDM.T_REVIEW_RULES;

---- ICDM-470 ---
CREATE OR REPLACE SYNONYM TABV_TOP_LEVEL_ENTITIES FOR DGS_ICDM.TABV_TOP_LEVEL_ENTITIES;

spool off

