spool c:\temp\table_updates.log

--------------------------------------------------------
--  August-15-2013  
--------------------------------------------------------

--
-- TABV_USE_CASE_GROUPS
--
-- New table for storing Use Case Groups
-- 
--

  CREATE TABLE TABV_USE_CASE_GROUPS
   (	GROUP_ID NUMBER NOT NULL, 
	PARENT_GROUP_ID NUMBER, 
	NAME_ENG VARCHAR2(100) NOT NULL, 
	NAME_GER VARCHAR2(100), 
	DESC_ENG VARCHAR2(255) NOT NULL, 
	DESC_GER VARCHAR2(255), 
	CREATED_USER VARCHAR2(30) NOT NULL, 
	CREATED_DATE TIMESTAMP (6) NOT NULL, 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_USER VARCHAR2(30), 
	VERSION NUMBER NOT NULL, 
	DELETED_FLAG VARCHAR2(1) DEFAULT 'N', 
	
	 CONSTRAINT USE_CASE_GROUPS_PK PRIMARY KEY (GROUP_ID), 
	 CONSTRAINT TABV_USE_CASE_GROUPS_UK1 UNIQUE (PARENT_GROUP_ID, NAME_ENG), 
	 
	 CONSTRAINT TABV_USE_CASE_GROUPS_FK1 FOREIGN KEY (PARENT_GROUP_ID) REFERENCES TABV_USE_CASE_GROUPS (GROUP_ID)
   );

--
-- TABV_USE_CASES
--
-- New table for storing Use Cases
-- 
--


  CREATE TABLE TABV_USE_CASES 
   (	USE_CASE_ID NUMBER NOT NULL, 
	GROUP_ID NUMBER NOT NULL, 
	NAME_ENG VARCHAR2(100) NOT NULL, 
	NAME_GER VARCHAR2(100), 
	DESC_ENG VARCHAR2(255) NOT NULL, 
	DESC_GER VARCHAR2(255), 
	CREATED_USER VARCHAR2(30) NOT NULL, 
	CREATED_DATE TIMESTAMP (6) NOT NULL, 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_USER VARCHAR2(30), 
	VERSION NUMBER NOT NULL, 
	DELETED_FLAG VARCHAR2(1) DEFAULT 'N', 
	
	 CONSTRAINT TABV_USE_CASES_PK PRIMARY KEY (USE_CASE_ID), 
	 CONSTRAINT TABV_USE_CASES_UK1 UNIQUE (GROUP_ID, NAME_ENG), 
	 
	 CONSTRAINT TABV_USE_CASES_FK1 FOREIGN KEY (GROUP_ID) REFERENCES TABV_USE_CASE_GROUPS (GROUP_ID)
   );

--
-- TABV_USE_CASE_SECTIONS
--
-- New table for storing Use Case Sections
-- 
--


  CREATE TABLE TABV_USE_CASE_SECTIONS
   (	SECTION_ID NUMBER NOT NULL, 
	USE_CASE_ID NUMBER NOT NULL, 
	NAME_ENG VARCHAR2(100) NOT NULL, 
	NAME_GER VARCHAR2(100), 
	DESC_ENG VARCHAR2(255) NOT NULL, 
	DESC_GER VARCHAR2(255), 
	PARENT_SECTION_ID NUMBER, 
	CREATED_USER VARCHAR2(30) NOT NULL, 
	CREATED_DATE TIMESTAMP (6) NOT NULL, 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_USER VARCHAR2(30), 
	VERSION NUMBER NOT NULL, 
	DELETED_FLAG VARCHAR2(1) DEFAULT 'N', 
	
	 CONSTRAINT TABV_USE_CASE_SECTIONS_PK PRIMARY KEY (SECTION_ID), 
	 CONSTRAINT TABV_USE_CASE_SECTIONS_UK1 UNIQUE (USE_CASE_ID, PARENT_SECTION_ID, NAME_ENG), 
	 
	 CONSTRAINT TABV_USE_CASE_SECTIONS_FK1 FOREIGN KEY (USE_CASE_ID) REFERENCES TABV_USE_CASES (USE_CASE_ID), 
	 CONSTRAINT TABV_USE_CASE_SECTIONS_FK2 FOREIGN KEY (PARENT_SECTION_ID) REFERENCES TABV_USE_CASE_SECTIONS (SECTION_ID)
   );

--
-- TABV_USE_CASE_POINTS
--
-- New table for storing Use Case Points
-- 
--
  CREATE TABLE TABV_USE_CASE_POINTS
   (	POINT_ID NUMBER NOT NULL, 
	USE_CASE_ID NUMBER NOT NULL, 
	SECTION_ID NUMBER NOT NULL, 
	NAME_ENG VARCHAR2(100) NOT NULL, 
	NAME_GER VARCHAR2(100), 
	DESC_ENG VARCHAR2(255) NOT NULL, 
	DESC_GER VARCHAR2(255), 
	CREATED_USER VARCHAR2(30) NOT NULL, 
	CREATED_DATE TIMESTAMP (6) NOT NULL, 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_USER VARCHAR2(30), 
	VERSION NUMBER NOT NULL, 
	DELETED_FLAG VARCHAR2(1) DEFAULT 'N', 
	
	 CONSTRAINT TABV_USE_CASE_POINTS_PK PRIMARY KEY (POINT_ID), 
	 CONSTRAINT TABV_USE_CASE_POINTS_UK1 UNIQUE (SECTION_ID, NAME_ENG), 
	 
	 CONSTRAINT TABV_USE_CASE_POINTS_FK1 FOREIGN KEY (USE_CASE_ID) REFERENCES TABV_USE_CASES (USE_CASE_ID), 
	 CONSTRAINT TABV_USE_CASE_POINTS_FK2 FOREIGN KEY (SECTION_ID) REFERENCES TABV_USE_CASE_SECTIONS (SECTION_ID)
   );


--
-- TABV_UCP_ATTRS
--
-- New table to provide mapping between use case points and attributes
-- 
--
  CREATE TABLE TABV_UCP_ATTRS
   (	UCPA_ID NUMBER NOT NULL, 
	USE_CASE_ID NUMBER NOT NULL, 
	SECTION_ID NUMBER NOT NULL, 
	POINT_ID NUMBER NOT NULL, 
	ATTR_ID NUMBER NOT NULL, 
	CREATED_USER VARCHAR2(30) NOT NULL, 
	CREATED_DATE TIMESTAMP (6) NOT NULL, 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_USER VARCHAR2(30), 
	VERSION NUMBER NOT NULL, 
	
	 CONSTRAINT TABV_UCP_ATTRS_PK PRIMARY KEY (UCPA_ID), 
	 CONSTRAINT TABV_UCP_ATTRS_UK1 UNIQUE (POINT_ID, ATTR_ID), 
	 
	 CONSTRAINT TABV_UCP_ATTRS_FK1 FOREIGN KEY (USE_CASE_ID) REFERENCES TABV_USE_CASES (USE_CASE_ID), 
	 CONSTRAINT TABV_UCP_ATTRS_FK2 FOREIGN KEY (SECTION_ID) REFERENCES TABV_USE_CASE_SECTIONS (SECTION_ID), 
	 CONSTRAINT TABV_UCP_ATTRS_FK3 FOREIGN KEY (POINT_ID) REFERENCES TABV_USE_CASE_POINTS (POINT_ID), 
	 CONSTRAINT TABV_UCP_ATTRS_FK4 FOREIGN KEY (ATTR_ID) REFERENCES TABV_ATTRIBUTES (ATTR_ID)
   );

    ALTER TABLE TABV_ATTRIBUTES
    ADD (PART_NUMBER_FLAG varchar2(1) default 'N',
    SPEC_LINK_FLAG varchar2(1) default 'N');

    ALTER TABLE TABV_PROJECT_ATTR ADD (PART_NUMBER varchar2(20) ,
    SPEC_LINK varchar2(1000) ,DESCRIPTION  varchar2(2000));       
       
    ALTER TABLE TABV_VARIANTS_ATTR ADD (PART_NUMBER varchar2(20) ,
    SPEC_LINK varchar2(1000) ,DESCRIPTION  varchar2(2000));
       
    ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR ADD (PART_NUMBER varchar2(20) ,
    SPEC_LINK varchar2(1000) ,DESCRIPTION  varchar2(2000));
    
    INSERT INTO TABV_ATTR_VALUE_TYPES VALUES(5,'HYPERLINK');

spool off
