spool c:\temp\15.grants.log

--
-- Grants for T_ALIAS_DETAILS,T_ALIAS_DEFINITION tables to DGS_ICDM_DEV_JPA user
--

GRANT DELETE, INSERT, SELECT, UPDATE ON T_ALIAS_DETAILS TO DGS_ICDM_JPA;
GRANT DELETE, INSERT, SELECT, UPDATE ON T_ALIAS_DEFINITION TO DGS_ICDM_JPA;

--
-- Icdm-1836 Grants for T_MANDATORY_ATTR tables to DGS_ICDM_DEV_JPA user
--
GRANT DELETE, INSERT, SELECT, UPDATE ON T_MANDATORY_ATTR TO DGS_ICDM_JPA;

--
--
--
GRANT SELECT, INSERT, UPDATE on TA2L_VCDM_VERSIONS to DGS_ICDM_JPA;                 
GRANT select on T_FUNCVERS_UNIQUE to DGS_ICDM_JPA;

REVOKE UPDATE on TA2L_FileInfo from DGS_ICDM_JPA;

GRANT EXECUTE on Set_SDOM_Info_for_A2L to dgs_icdm_jpa;

spool off
