spool c:\temp\table_updates.log

--------------------------------------------------------
--  January-29-2016  
--------------------------------------------------------

--
-- ICDM-1836
-- T_MANDATORY_ATTR
--
-- New table for storing mandatory attributes list against VALUE_ID of TABV_ATTR_VALUES
-- 
--

  CREATE TABLE T_MANDATORY_ATTR
   (MA_ID NUMBER NOT NULL, 
    DEF_VALUE_ID NUMBER NOT NULL, 
    ATTR_ID NUMBER NOT NULL, 
    CREATED_USER VARCHAR2(30) NOT NULL, 
    CREATED_DATE TIMESTAMP (6) NOT NULL, 
    MODIFIED_DATE TIMESTAMP (6), 
    MODIFIED_USER VARCHAR2(30), 
    VERSION NUMBER NOT NULL, 
    
    CONSTRAINT T_MANDATORY_ATTR_PK PRIMARY KEY (MA_ID), 
    CONSTRAINT  T_MANDATORY_ATTR_UK1 UNIQUE (DEF_VALUE_ID, ATTR_ID),
     
     
    CONSTRAINT  T_MANDATORY_ATTR_FK1 FOREIGN KEY (DEF_VALUE_ID) REFERENCES TABV_ATTR_VALUES (VALUE_ID),
    CONSTRAINT  T_MANDATORY_ATTR_FK2 FOREIGN KEY (ATTR_ID) REFERENCES TABV_ATTRIBUTES (ATTR_ID)
   );


--------------------------------------------------------
--  Feb-02-2016  
--------------------------------------------------------

--
-- ICDM-1842
-- T_MANDATORY_ATTR
--
-- Additional columns for storing Vcdm_A2l_Name and Vcdm_A2l_Date for a TPIDCA2L
-- 
--  
ALTER TABLE T_PIDC_A2L ADD VCDM_A2L_NAME VARCHAR2(200); 

ALTER TABLE T_PIDC_A2L ADD VCDM_A2L_DATE TIMESTAMP (6);


CREATE TABLE T_FUNCVERS_UNIQUE
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FUNCNAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"FUNCVERSION" VARCHAR2(255 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	 CONSTRAINT "PK_FUNCVERSUNI" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS" 
;

--------------------------------------------------------
--  DDL for Index IDX_FUNCVERSUNI_FUNCNAME
--------------------------------------------------------

  CREATE INDEX IDX_FUNCVERSUNI_FUNCNAME ON T_FUNCVERS_UNIQUE (FUNCNAME) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS" 
;

--------------------------------------------------------
--  DDL for Index IDX_FUNCVERSUNI_UKFUNCVERS
--------------------------------------------------------

  CREATE UNIQUE INDEX IDX_FUNCVERSUNI_UKFUNCVERS ON T_FUNCVERS_UNIQUE (FUNCNAME, FUNCVERSION) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DGS_ICDM_TS" 
;

spool off
