--
--
--
CREATE OR REPLACE FORCE VIEW TA2L_VCDM_VERSIONS 
  (  "VERS_NUMMER"
   , "ORIGINAL_FILE"
   , "PST"
   , "VCDM_CHECKSUM"
   , "A2L_CHECKSUM"
   , "FILESIZE"
   , "VCDM_COMMENT"
   , "ORIGINAL_DATE"
  ) AS 
  select "VERS_NUMMER"
       , "ORIGINAL_FILE"
       , "PST"
       , "VCDM_CHECKSUM"
       , "A2L_CHECKSUM"
       , "FILESIZE"
       , "VCDM_COMMENT"
       , "ORIGINAL_DATE"
  from TA2L_VCDM_VERSIONS@DGSPRO.WORLD@K5ESK_VILLA_RO
;


--
-- ICDM-1671
--
CREATE OR REPLACE FORCE VIEW TA2L_FILEINFO
  (  "ID"
   , "ASAP2VERSION"
   , "A2LFILESIZE"
   , "A2LFILECHECKSUM"
   , "HEADERVERSION"
   , "PROJECTLONGIDENTIFIER"
   , "FILENAME"
   , "HEADERCOMMENT"
   , "HEADERPROJECTNO"
   , "PROJECTNAME"
   , "SDOM_PVER_NAME"
   , "SDOM_PVER_VARIANT"
   , "SDOM_PVER_VERSID"
   , "VCDM_A2LFILE_ID"
   , "SDOM_PVER_REVISION"
   , "FILEDATE"
   ) AS 
		select "ID"
			 , "ASAP2VERSION"
			 , "A2LFILESIZE"
			 , "A2LFILECHECKSUM"
			 , "HEADERVERSION"
			 , "PROJECTLONGIDENTIFIER"
			 , "FILENAME"
			 , "HEADERCOMMENT"
			 , "HEADERPROJECTNO"
			 , "PROJECTNAME"
			 , "SDOM_PVER_NAME"
			 , "SDOM_PVER_VARIANT"
			 , "SDOM_PVER_VERSID"
			 , "VCDM_A2LFILE_ID"
			 , "SDOM_PVER_REVISION" 
			 , vver.ORIGINAL_DATE
		 from TA2L_FILEINFO@DGSPRO.WORLD@K5ESK_VILLA_RO  afi
			, TA2L_VCDM_VERSIONS@DGSPRO.WORLD@K5ESK_VILLA_RO  vver
		where afi.vcdm_a2lfile_id = vver.vers_nummer     (+)
;