spool c:\temp\06_synonyms.log



-- ICDM-2189 create SYNONYM in ICDM JPA

CREATE OR REPLACE SYNONYM T_QNAIRE_ANS_OPEN_POINTS for DGS_ICDM.T_QNAIRE_ANS_OPEN_POINTS;


-- ICDM-2295 create SYNONYM in ICDM JPA

CREATE OR REPLACE SYNONYM T_GROUP_ATTR_VALUES for DGS_ICDM.T_GROUP_ATTR_VALUES;
  
  CREATE OR REPLACE SYNONYM T_GROUP_ATTR_VALIDITY for DGS_ICDM.T_GROUP_ATTR_VALIDITY;


spool off