spool c:\temp\01_table_alters_fc2wp.log

-------------------------------------------------
--Task 231531 Schema for FC2WP definition
-------------------------------------------------
CREATE TABLE T_BASE_COMPONENTS
  (
    BC_ID         NUMBER NOT NULL ,
    BC_NAME       VARCHAR2 (255) NOT NULL ,
    BC_DESC       VARCHAR2 (4000) ,
    CREATED_USER  VARCHAR2 (30) NOT NULL ,
    CREATED_DATE  TIMESTAMP NOT NULL ,
    MODIFIED_USER VARCHAR2 (30) ,
    MODIFIED_DATE TIMESTAMP ,
    VERSION       NUMBER NOT NULL
  ) ;
ALTER TABLE T_BASE_COMPONENTS ADD CONSTRAINT T_BASE_COMPONENTS_PK PRIMARY KEY ( BC_ID ) ;
ALTER TABLE T_BASE_COMPONENTS ADD CONSTRAINT T_BASE_COMPONENTS__UN UNIQUE ( BC_NAME ) ;

CREATE TABLE T_FC2WP_DEFINITION
  (
    FCWP_DEF_ID          NUMBER NOT NULL ,
    NAME_VALUE_ID        NUMBER (15) NOT NULL ,
    DIV_VALUE_ID         NUMBER (15) NOT NULL ,
    RELV_FOR_QNAIRE_FLAG VARCHAR2 (1) ,
    CREATED_USER         VARCHAR2 (30) NOT NULL ,
    CREATED_DATE         TIMESTAMP NOT NULL ,
    MODIFIED_USER        VARCHAR2 (30) ,
    MODIFIED_DATE        TIMESTAMP ,
    VERSION              NUMBER NOT NULL
  ) ;
COMMENT ON COLUMN T_FC2WP_DEFINITION.RELV_FOR_QNAIRE_FLAG
IS
  'Options
Y - relevant
N - not relevant. Default value
Nullable. Null means N' ;
  ALTER TABLE T_FC2WP_DEFINITION ADD CONSTRAINT T_FC2WP_DEFINITION_PK PRIMARY KEY ( FCWP_DEF_ID ) ;
  ALTER TABLE T_FC2WP_DEFINITION ADD CONSTRAINT T_FC2WP_DEFINITION__UN UNIQUE ( NAME_VALUE_ID , DIV_VALUE_ID ) ;

CREATE TABLE T_FC2WP_DEF_VERSION
    (
      FCWP_VER_ID       NUMBER NOT NULL ,
      FCWP_DEF_ID       NUMBER NOT NULL ,
      DESC_ENG          VARCHAR2 (4000) NOT NULL ,
      DESC_GER          VARCHAR2 (4000) ,
      MAJOR_VERSION_NUM NUMBER NOT NULL ,
      MINOR_VERSION_NUM NUMBER ,
      ACTIVE_FLAG       VARCHAR2 (1) ,
      ARCH_RELEASE_SDOM VARCHAR2 (100) ,
      IN_WORK_FLAG      VARCHAR2 (1) ,
      CREATED_USER      VARCHAR2 (30) NOT NULL ,
      CREATED_DATE      TIMESTAMP NOT NULL ,
      MODIFIED_USER     VARCHAR2 (30) ,
      MODIFIED_DATE     TIMESTAMP ,
      VERSION           NUMBER NOT NULL
    ) ;
  ALTER TABLE T_FC2WP_DEF_VERSION ADD CONSTRAINT FC2WP_DEF_VERSION_PK PRIMARY KEY ( FCWP_VER_ID ) ;
  ALTER TABLE T_FC2WP_DEF_VERSION ADD CONSTRAINT T_FC2WP_DEF_VERSION__UN UNIQUE ( FCWP_DEF_ID , MAJOR_VERSION_NUM , MINOR_VERSION_NUM ) ;

CREATE TABLE T_FC2WP_MAPPING
    (
      FCWP_MAP_ID            NUMBER NOT NULL ,
      FCWP_VER_ID            NUMBER NOT NULL ,
      FUNCTION_ID            NUMBER NOT NULL ,
      WP_DIV_ID              NUMBER (15) ,
      AGREED_WITH_COC_FLAG   VARCHAR2 (1) ,
      AGREED_DATE            TIMESTAMP ,
      RESP_FOR_AGR_USER_ID   NUMBER ,
      USE_WP_DEFAULTS_FLAG   VARCHAR2 (1) ,
      CONTACT_USER_ID        NUMBER ,
      SECOND_CONTACT_USER_ID NUMBER ,
      BC_ID                  NUMBER ,
      COMMENTS               VARCHAR2 (4000) ,
      IN_ICDM_A2L_FLAG       VARCHAR2 (1) ,
      DELETE_FLAG            VARCHAR2 (1) ,
      CREATED_USER           VARCHAR2 (30) NOT NULL ,
      CREATED_DATE           TIMESTAMP NOT NULL ,
      MODIFIED_USER          VARCHAR2 (30) ,
      MODIFIED_DATE          TIMESTAMP ,
      VERSION                NUMBER NOT NULL
    ) ;
  COMMENT ON COLUMN T_FC2WP_MAPPING.AGREED_WITH_COC_FLAG
IS
  'Y - Agreed
N - Not agreed
null - N(not agreed)' ;
  COMMENT ON COLUMN T_FC2WP_MAPPING.USE_WP_DEFAULTS_FLAG
IS
  'Y - Use defaults(from WP)
N - use local definition
null - Y (use from wp)' ;
  ALTER TABLE T_FC2WP_MAPPING ADD CONSTRAINT T_FC2WP_MAPPING_PK PRIMARY KEY ( FCWP_MAP_ID ) ;
  ALTER TABLE T_FC2WP_MAPPING ADD CONSTRAINT T_FC2WP_MAPPING__UN UNIQUE ( FCWP_VER_ID , FUNCTION_ID ) ;
  CREATE INDEX T_FC2WP_MAPPING_IDX1 ON T_FC2WP_MAPPING (FCWP_VER_ID) ;
  
CREATE TABLE T_FC2WP_PT_TYPE_RELV
    (
      FCWP_PT_TYPE_RELV_ID NUMBER NOT NULL ,
      FCWP_DEF_ID          NUMBER NOT NULL ,
      PT_TYPE_ID           NUMBER NOT NULL ,
      CREATED_USER         VARCHAR2 (30) NOT NULL ,
      CREATED_DATE         TIMESTAMP NOT NULL ,
      MODIFIED_USER        VARCHAR2 (30) ,
      MODIFIED_DATE        TIMESTAMP ,
      VERSION              NUMBER NOT NULL
    ) ;
  ALTER TABLE T_FC2WP_PT_TYPE_RELV ADD CONSTRAINT T_FC2WP_PT_TYPE_RELV_PK PRIMARY KEY ( FCWP_PT_TYPE_RELV_ID ) ;
  ALTER TABLE T_FC2WP_PT_TYPE_RELV ADD CONSTRAINT T_FC2WP_PT_TYPE_RELV__UN UNIQUE ( FCWP_DEF_ID , PT_TYPE_ID ) ;
  
CREATE TABLE T_FC2WP_MAP_PT_TYPES
    (
      FCWP_MAP_PT_TYPE_ID NUMBER NOT NULL ,
      FCWP_MAP_ID         NUMBER NOT NULL ,
      PT_TYPE_ID          NUMBER (15) NOT NULL ,
      CREATED_USER        VARCHAR2 (30) NOT NULL ,
      CREATED_DATE        TIMESTAMP NOT NULL ,
      MODIFIED_USER       VARCHAR2 (30) ,
      MODIFIED_DATE       TIMESTAMP ,
      VERSION             NUMBER NOT NULL
    ) ;
  ALTER TABLE T_FC2WP_MAP_PT_TYPES ADD CONSTRAINT T_FC2WP_MAP_PT_TYPES_PK PRIMARY KEY ( FCWP_MAP_PT_TYPE_ID ) ;
  ALTER TABLE T_FC2WP_MAP_PT_TYPES ADD CONSTRAINT T_FC2WP_MAP_PT_TYPES__UN UNIQUE ( FCWP_MAP_ID , PT_TYPE_ID ) ;

CREATE TABLE T_POWER_TRAIN_TYPE
    (
      PT_TYPE_ID    NUMBER NOT NULL ,
      PT_TYPE       VARCHAR2 (50) NOT NULL ,
      PT_TYPE_DESC  VARCHAR2 (4000) ,
      CREATED_USER  VARCHAR2 (30) NOT NULL ,
      CREATED_DATE  TIMESTAMP NOT NULL ,
      MODIFIED_USER VARCHAR2 (30) ,
      MODIFIED_DATE TIMESTAMP ,
      VERSION       NUMBER NOT NULL
    ) ;
  ALTER TABLE T_POWER_TRAIN_TYPE ADD CONSTRAINT T_POWER_TRAIN_TYPE_PK PRIMARY KEY ( PT_TYPE_ID ) ;
  ALTER TABLE T_POWER_TRAIN_TYPE ADD CONSTRAINT T_POWER_TRAIN_TYPE__UN UNIQUE ( PT_TYPE ) ;

CREATE TABLE T_WP_RESOURCE
    (
      WP_RES_ID     NUMBER NOT NULL ,
      RESOURCE_CODE VARCHAR2 (40) NOT NULL ,
      RESOURCE_DESC VARCHAR2 (4000) ,
      CREATED_USER  VARCHAR2 (30) NOT NULL ,
      CREATED_DATE  TIMESTAMP NOT NULL ,
      MODIFIED_USER VARCHAR2 (30) ,
      MODIFIED_DATE TIMESTAMP ,
      VERSION       NUMBER NOT NULL
    ) ;
  ALTER TABLE T_WP_RESOURCE ADD CONSTRAINT T_WP_RESOURCE_PK PRIMARY KEY ( WP_RES_ID ) ;
  ALTER TABLE T_WP_RESOURCE ADD CONSTRAINT T_WP_RESOURCE__UN UNIQUE ( RESOURCE_CODE ) ;

--Foreign Keys
ALTER TABLE T_FC2WP_DEFINITION ADD CONSTRAINT T_FC2WP_DEFINITION__FK1 FOREIGN KEY ( NAME_VALUE_ID ) REFERENCES TABV_ATTR_VALUES ( VALUE_ID ) ;
ALTER TABLE T_FC2WP_DEFINITION ADD CONSTRAINT T_FC2WP_DEFINITION__FK2 FOREIGN KEY ( DIV_VALUE_ID ) REFERENCES TABV_ATTR_VALUES ( VALUE_ID ) ;
ALTER TABLE T_FC2WP_DEF_VERSION ADD CONSTRAINT T_FC2WP_DEF_VERSION__FK1 FOREIGN KEY ( FCWP_DEF_ID ) REFERENCES T_FC2WP_DEFINITION ( FCWP_DEF_ID ) ;
ALTER TABLE T_FC2WP_MAPPING ADD CONSTRAINT T_FC2WP_MAPPING__FK1 FOREIGN KEY ( CONTACT_USER_ID ) REFERENCES TABV_APIC_USERS ( USER_ID ) ;
ALTER TABLE T_FC2WP_MAPPING ADD CONSTRAINT T_FC2WP_MAPPING__FK2 FOREIGN KEY ( SECOND_CONTACT_USER_ID ) REFERENCES TABV_APIC_USERS ( USER_ID ) ;
ALTER TABLE T_FC2WP_MAPPING ADD CONSTRAINT T_FC2WP_MAPPING__FK3 FOREIGN KEY ( RESP_FOR_AGR_USER_ID ) REFERENCES TABV_APIC_USERS ( USER_ID ) ;
ALTER TABLE T_FC2WP_MAPPING ADD CONSTRAINT T_FC2WP_MAPPING__FK4 FOREIGN KEY ( BC_ID ) REFERENCES T_BASE_COMPONENTS ( BC_ID ) ;
ALTER TABLE T_FC2WP_MAPPING ADD CONSTRAINT T_FC2WP_MAPPING__FK5 FOREIGN KEY ( FCWP_VER_ID ) REFERENCES T_FC2WP_DEF_VERSION ( FCWP_VER_ID ) ;
ALTER TABLE T_FC2WP_MAPPING ADD CONSTRAINT T_FC2WP_MAPPING__FK6 FOREIGN KEY ( FUNCTION_ID ) REFERENCES T_FUNCTIONS ( ID ) ;
ALTER TABLE T_FC2WP_MAPPING ADD CONSTRAINT T_FC2WP_MAPPING__FK7 FOREIGN KEY ( WP_DIV_ID ) REFERENCES T_WORKPACKAGE_DIVISION ( WP_DIV_ID ) ;
ALTER TABLE T_FC2WP_PT_TYPE_RELV ADD CONSTRAINT T_FC2WP_PT_TYPE_RELV__FK1 FOREIGN KEY ( FCWP_DEF_ID ) REFERENCES T_FC2WP_DEFINITION ( FCWP_DEF_ID ) ;
ALTER TABLE T_FC2WP_PT_TYPE_RELV ADD CONSTRAINT T_FC2WP_PT_TYPE_RELV__FK2 FOREIGN KEY ( PT_TYPE_ID ) REFERENCES T_POWER_TRAIN_TYPE ( PT_TYPE_ID ) ;
ALTER TABLE T_FC2WP_MAP_PT_TYPES ADD CONSTRAINT T_FC2WP_MAP_PT_TYPES__FK1 FOREIGN KEY ( FCWP_MAP_ID ) REFERENCES T_FC2WP_MAPPING ( FCWP_MAP_ID ) ;
ALTER TABLE T_FC2WP_MAP_PT_TYPES ADD CONSTRAINT T_FC2WP_MAP_PT_TYPES__FK2 FOREIGN KEY ( PT_TYPE_ID ) REFERENCES T_POWER_TRAIN_TYPE ( PT_TYPE_ID ) ;
  
  
--Changes in existing tables

--T_WORKPACKAGE
ALTER TABLE T_WORKPACKAGE ADD(
    DESC_ENG      VARCHAR2 (4000) ,
    DESC_GER      VARCHAR2 (4000) ,
    DELETE_FLAG   VARCHAR2 (1)
  ) ;
COMMENT ON COLUMN T_WORKPACKAGE.DELETE_FLAG
IS
  'Possible values
Y-Deleted
N-Not deleted
null = Not deleted' ;

ALTER TABLE T_WORKPACKAGE MODIFY (WP_GROUP NULL);

--T_WORKPACKAGE_DIVISION
ALTER TABLE T_WORKPACKAGE_DIVISION ADD(
    WP_RES_ID              NUMBER ,
    WP_ID_MCR              VARCHAR2 (50) ,
    DELETE_FLAG            VARCHAR2 (1) ,
    CONTACT_USER_ID        NUMBER ,
    SECOND_CONTACT_USER_ID NUMBER
  ) ;
  COMMENT ON COLUMN T_WORKPACKAGE_DIVISION.DELETE_FLAG
IS
  'Possible values
Y-Deleted
N-Not deleted
null = Not deleted' ;
  ALTER TABLE T_WORKPACKAGE_DIVISION ADD CONSTRAINT T_WORKPACKAGE_DIVISION_FK_3 FOREIGN KEY ( CONTACT_USER_ID ) REFERENCES TABV_APIC_USERS ( USER_ID ) ;
  ALTER TABLE T_WORKPACKAGE_DIVISION ADD CONSTRAINT T_WORKPACKAGE_DIVISION_FK_4 FOREIGN KEY ( SECOND_CONTACT_USER_ID ) REFERENCES TABV_APIC_USERS ( USER_ID ) ;
  ALTER TABLE T_WORKPACKAGE_DIVISION ADD CONSTRAINT T_WORKPACKAGE_DIVISION_FK_5 FOREIGN KEY ( WP_RES_ID ) REFERENCES T_WP_RESOURCE ( WP_RES_ID ) ;
  

spool off