spool c:\temp\table_alters.log

-------------------------------------------------
--Story 221726 T_ALTERNATE_ATTR Table creation
------------------------------------------------- 
CREATE TABLE T_ALTERNATE_ATTR (
    ATTR_PK NUMBER(15,0) NOT NULL PRIMARY KEY,
    ATTR_ID NUMBER(15,0) NOT NULL ,
    ALTERNATE_ATTR_ID NUMBER(15,0) NOT NULL,
    CREATED_DATE TIMESTAMP(6),
    CREATED_USER VARCHAR2(30 BYTE),
    MODIFIED_DATE TIMESTAMP(6),
    MODIFIED_USER VARCHAR2(30 BYTE),
    VERSION NUMBER
);

--Add unique constraint to T_ALTERNATE_ATTR column
ALTER TABLE T_ALTERNATE_ATTR
ADD CONSTRAINT attr_id_uniq UNIQUE (ATTR_ID);


----T_RVW_RESULTS_SECONDARY
CREATE TABLE T_RVW_RESULTS_SECONDARY
  (
    SEC_REVIEW_ID NUMBER (15) NOT NULL ,
    RESULT_ID     NUMBER NOT NULL ,
    RSET_ID       NUMBER (15) ,
    CREATED_DATE  TIMESTAMP NOT NULL ,
    CREATED_USER  VARCHAR2 (30 BYTE) NOT NULL ,
    MODIFIED_DATE TIMESTAMP ,
    MODIFIED_USER VARCHAR2 (30 BYTE) ,
    VERSION       NUMBER NOT NULL
  );
  
    ----ALTER Scripts
ALTER TABLE T_RVW_RESULTS_SECONDARY ADD CONSTRAINT T_RVW_RESULTS_SECONDARY_PK PRIMARY KEY ( SEC_REVIEW_ID ) ;
ALTER TABLE T_RVW_RESULTS_SECONDARY ADD CONSTRAINT T_RVW_RESULTS_SECONDARY_FK1 FOREIGN KEY ( RESULT_ID ) REFERENCES T_RVW_RESULTS ( RESULT_ID ) ;
ALTER TABLE T_RVW_RESULTS_SECONDARY ADD CONSTRAINT T_RVW_RESULTS_SECONDARY_FK2 FOREIGN KEY ( RSET_ID ) REFERENCES T_RULE_SET ( RSET_ID ) ;
alter table T_RVW_RESULTS_SECONDARY add CONSTRAINT T_RVW_RESULTS_SECONDARY_UQ1  UNIQUE  ( RESULT_ID,RSET_ID );

  ----T_RVW_PARAMETERS_SECONDARY

CREATE TABLE T_RVW_PARAMETERS_SECONDARY
  (
    SEC_RVW_PARAM_ID NUMBER (15) NOT NULL ,
    RVW_PARAM_ID     NUMBER NOT NULL ,
    SEC_REVIEW_ID    NUMBER (15) NOT NULL ,
    LOWER_LIMIT      NUMBER (15) ,
    UPPER_LIMIT      NUMBER ,
    REF_VALUE BLOB ,
    REF_UNIT       VARCHAR2 (255 BYTE) ,
    RESULT         VARCHAR2 (1 BYTE) ,
    CHANGE_FLAG    NUMBER (6) ,
    MATCH_REF_FLAG VARCHAR2 (1 BYTE) ,
    BITWISE_LIMIT  VARCHAR2 (400 BYTE) ,
    ISBITWISE      VARCHAR2 (1 BYTE) ,
    LAB_OBJ_ID     NUMBER ,
    REV_ID         NUMBER ,
    CREATED_DATE   TIMESTAMP NOT NULL ,
    CREATED_USER   VARCHAR2 (30 BYTE) NOT NULL ,
    MODIFIED_DATE  TIMESTAMP ,
    MODIFIED_USER  VARCHAR2 (30 BYTE) ,
    RVW_METHOD   VARCHAR2 (1 BYTE)
    VERSION        NUMBER NOT NULL
  );
  
      ----ALTER Scripts
ALTER TABLE T_RVW_PARAMETERS_SECONDARY ADD CONSTRAINT T_RVW_PARAMETERS_SECONDARY_PK PRIMARY KEY ( SEC_RVW_PARAM_ID ) ;
ALTER TABLE T_RVW_PARAMETERS_SECONDARY ADD CONSTRAINT T_RVW_PARAMETERS_SECONDARY_FK1 FOREIGN KEY ( RVW_PARAM_ID ) REFERENCES T_RVW_PARAMETERS ( RVW_PARAM_ID )  ;
ALTER TABLE T_RVW_PARAMETERS_SECONDARY ADD CONSTRAINT T_RVW_PARAMETERS_SECONDARY_FK2 FOREIGN KEY ( SEC_REVIEW_ID ) REFERENCES T_RVW_RESULTS_SECONDARY ( SEC_REVIEW_ID )  ;


alter table T_RVW_PARAMETERS add(secondary_result varchar2(1));

----------------------------------------------------------------
--Task 236308 - Mark the secondary review status as 'checked'
----------------------------------------------------------------
ALTER TABLE T_RVW_PARAMETERS add(SECONDARY_RESULT_STATE varchar2(1));

--Rename the column to identify that it represents the division name
ALTER TABLE T_WORKPACKAGE_DIVISION RENAME COLUMN VALUE_ID TO DIV_VALUE_ID;


----------------------------------------------------------------
--Task  - Use new column WP_DIV_ID to identify wp name, instead of FC2WP_ID
----------------------------------------------------------------
ALTER TABLE T_RVW_RESULTS ADD WP_DIV_ID NUMBER;

ALTER TABLE  T_RVW_RESULTS ADD  CONSTRAINT T_RVW_RESULTS_FK5  FOREIGN KEY (WP_DIV_ID) REFERENCES T_WORKPACKAGE_DIVISION(WP_DIV_ID);

-----------------------------------------------------------------------------------------------
--Task 238117 - DB changes for mandatory rule set for a PIDC
-----------------------------------------------------------------------------------------------

  --ALTERING T_RULE_SET to add a new column for mapping attribute value id
   ALTER TABLE T_RULE_SET ADD ATTR_VALUE_ID NUMBER REFERENCES TABV_ATTR_VALUES(VALUE_ID);
   
spool off
