spool c:\temp\02_Table_Alters2.log

------------------------------------------------------------------------------------------------------------------
--  ALM TaskId : 553722: DB changes - new table has to be created to store the assessment and 
--    result for every individual questions and also data has to be inserted for existing questions
------------------------------------------------------------------------------------------------------------------

-- create T_QUESTION_RESULT_OPTIONS
CREATE TABLE T_QUESTION_RESULT_OPTIONS
(
      Q_RESULT_OPT_ID NUMBER NOT NULL
    , Q_ID NUMBER NOT NULL 
    , Q_RESULT_NAME VARCHAR2(1000) NOT NULL 
    , Q_RESULT_TYPE VARCHAR2(500) NOT NULL 
    , CREATED_DATE TIMESTAMP NOT NULL 
    , CREATED_USER VARCHAR2(100) NOT NULL 
    , MODIFIED_DATE TIMESTAMP  
    , MODIFIED_USER VARCHAR2(100)  
    , VERSION NUMBER NOT NULL
    
    , CONSTRAINT T_QUESTION_RESULT_OPT_PK1 PRIMARY KEY (Q_RESULT_OPT_ID)

    , CONSTRAINT T_QUESTION_RESULT_OPT_UK1 UNIQUE (Q_ID, Q_RESULT_NAME)
    , CONSTRAINT T_QUESTION_RESULT_OPT_UK2 UNIQUE (Q_ID, Q_RESULT_NAME, Q_RESULT_TYPE)

    , CONSTRAINT T_QUESTION_RESULT_OPT_FK1 FOREIGN KEY (Q_ID) REFERENCES T_QUESTION(Q_ID)
);

--Altering T_RVW_QNAIRE_ANSWER for storing T_QUESTION_RESULT_OPTIONS id

ALTER TABLE T_RVW_QNAIRE_ANSWER 
    ADD Q_RESULT_OPT_ID NUMBER ;

ALTER TABLE T_RVW_QNAIRE_ANSWER 
    ADD CONSTRAINT T_RVW_QNAIRE_ANSWERS__FK_6
        FOREIGN KEY(Q_RESULT_OPT_ID)
        REFERENCES T_QUESTION_RESULT_OPTIONS(Q_RESULT_OPT_ID);

------------------------------------------------------------------------------------------------------------------
--  ALM TaskId : 555532: DB changes for 100% CDFx delivery documentation
------------------------------------------------------------------------------------------------------------------
        
--T_CDFX_DELIVERY
CREATE TABLE T_CDFX_DELIVERY (
   CDFX_DELIVERY_ID NUMBER NOT NULL, 
    PIDC_A2L_ID NUMBER NOT NULL , 
    VARIANT_ID NUMBER, 
    WP_DEFN_VERS_ID NUMBER NOT NULL , 
    SCOPE VARCHAR2(1), 
    READINESS_YN VARCHAR2(1) NOT NULL, 
    CREATED_DATE TIMESTAMP NOT NULL, 
    CREATED_USER VARCHAR2(20) NOT NULL, 
    MODIFIED_DATE TIMESTAMP, 
    MODIFIED_USER VARCHAR2(20), 
    VERSION NUMBER NOT NULL
);
    
ALTER TABLE T_CDFX_DELIVERY ADD CONSTRAINT T_CDFX_DELIVERY_PK PRIMARY KEY (CDFX_DELIVERY_ID);
ALTER TABLE T_CDFX_DELIVERY ADD CONSTRAINT T_CDFX_DELIVERY_FK1 FOREIGN KEY (PIDC_A2L_ID) REFERENCES T_PIDC_A2L (PIDC_A2L_ID) ;
ALTER TABLE T_CDFX_DELIVERY ADD CONSTRAINT T_CDFX_DELIVERY_FK2 FOREIGN KEY (VARIANT_ID) REFERENCES TABV_PROJECT_VARIANTS (VARIANT_ID) ;
ALTER TABLE T_CDFX_DELIVERY ADD CONSTRAINT T_CDFX_DELIVERY_FK3 FOREIGN KEY (WP_DEFN_VERS_ID) REFERENCES T_A2L_WP_DEFN_VERSIONS (WP_DEFN_VERS_ID) ;
    
-------------------------------T_CDFX_DELVRY_WP_RESP---------------------------------
    
CREATE TABLE T_CDFX_DELVRY_WP_RESP (
    CDFX_DEL_WP_RESP_ID NUMBER NOT NULL, 
    CDFX_DELIVERY_ID NUMBER NOT NULL, 
    WP_ID NUMBER NOT NULL, 
    RESP_ID NUMBER NOT NULL, 
    CREATED_DATE TIMESTAMP NOT NULL, 
    CREATED_USER VARCHAR2(20) NOT NULL, 
    MODIFIED_DATE TIMESTAMP, 
    MODIFIED_USER VARCHAR2(20), 
    VERSION NUMBER NOT NULL
);
    
    
ALTER TABLE T_CDFX_DELVRY_WP_RESP ADD CONSTRAINT T_CDFX_DEL_WP_RESP_PK PRIMARY KEY (CDFX_DEL_WP_RESP_ID);
     
ALTER TABLE T_CDFX_DELVRY_WP_RESP ADD CONSTRAINT T_CDFX_DEL_WP_RESP_UK1 UNIQUE (CDFX_DELIVERY_ID, WP_ID,RESP_ID);
   
ALTER TABLE T_CDFX_DELVRY_WP_RESP 
    ADD CONSTRAINT T_CDFX_DEL_WP_RESP_FK1 
        FOREIGN KEY (CDFX_DELIVERY_ID) 
        REFERENCES T_CDFX_DELIVERY (CDFX_DELIVERY_ID);
        

ALTER TABLE T_CDFX_DELVRY_WP_RESP ADD CONSTRAINT T_CDFX_DEL_WP_RESP_FK2 FOREIGN KEY (WP_ID) REFERENCES T_A2L_WORK_PACKAGES (A2L_WP_ID);
ALTER TABLE T_CDFX_DELVRY_WP_RESP ADD CONSTRAINT T_CDFX_DEL_WP_RESP_FK3 FOREIGN KEY (RESP_ID) REFERENCES T_A2L_RESPONSIBILITY (A2L_RESP_ID);
   
------------------------------T_CDFX_DELVRY_PARAM----------------------------------------
CREATE TABLE T_CDFX_DELVRY_PARAM (  
    CDFX_DELVRY_PARAM_ID NUMBER NOT NULL, 
    CDFX_DELVRY_WP_RESP_ID NUMBER NOT NULL, 
    PARAM_ID NUMBER NOT NULL , 
    RVW_RESULT_ID NUMBER NOT NULL , 
    CREATED_DATE TIMESTAMP (6) NOT NULL , 
    CREATED_USER VARCHAR2(20 BYTE) NOT NULL , 
    MODIFIED_DATE TIMESTAMP (6), 
    MODIFIED_USER VARCHAR2(20 BYTE), 
    VERSION NUMBER NOT NULL , 
    
    CONSTRAINT T_CDFX_DELVRY_PARAM_PK PRIMARY KEY (CDFX_DELVRY_PARAM_ID),
    CONSTRAINT T_CDFX_DELVRY_PARAM_FK1 FOREIGN KEY (PARAM_ID)
        REFERENCES T_PARAMETER (ID) , 
    CONSTRAINT T_CDFX_DELVRY_PARAM_FK2 FOREIGN KEY (RVW_RESULT_ID)
        REFERENCES T_RVW_RESULTS (RESULT_ID) , 
    CONSTRAINT T_CDFX_DELVRY_PARAM_FK3 FOREIGN KEY (CDFX_DELVRY_WP_RESP_ID)
        REFERENCES T_CDFX_DELVRY_WP_RESP (CDFX_DEL_WP_RESP_ID)
);

ALTER TABLE T_CDFX_DELVRY_PARAM ADD CONSTRAINT T_CDFX_DELVRY_PARAM_UK1 UNIQUE (CDFX_DELVRY_WP_RESP_ID, PARAM_ID);


spool off
