CREATE OR REPLACE VIEW DGS_ICDM.V_LDB2_FEATURES ( FEATURE_ID, FEATURE_TEXT )
AS
  SELECT SSDF.FEATURE_ID,
    DECODE(SSDF.FEATURE_TEXT, NULL, ATTR.ATTR_NAME_ENG, SSDF.FEATURE_TEXT) AS FEATURE_TEXT
  FROM T_SSD_FEATURES SSDF,
    TABV_ATTRIBUTES ATTR
  WHERE SSDF.APIC_ATTR_ID = ATTR.ATTR_ID(+)
  AND SSDF.ICDM_ONLY     != 'Y' ;

CREATE OR REPLACE VIEW V_LDB2_VALUES ( VALUE_ID, FEATURE_ID, VALUE_TEXT )
AS
  SELECT SSDV.VALUE_ID,
    SSDV.FEATURE_ID,
    DECODE(SSDV.VALUE_TEXT, NULL, AVAL.TEXTVALUE_ENG, SSDV.VALUE_TEXT) AS VALUE_TEXT
  FROM DGS_ICDM.T_SSD_VALUES SSDV,
    DGS_ICDM.TABV_ATTR_VALUES AVAL
  WHERE SSDV.APIC_VALUE_ID = AVAL.VALUE_ID(+) ;
