spool c:\temp\02_Table_Alters_a2lresp.log

------------------------------------------------------------------------------------------------------------------
-- ALM Task ID : 463370
-- A2L Responsibility tables Create scripts and related alters
------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------
--T_A2L_RESPONSIBILITY
------------------------------------------------------------------------------------
CREATE TABLE T_A2L_RESPONSIBILITY 
   (    
    A2L_RESP_ID NUMBER NOT NULL, 
    PROJECT_ID NUMBER NOT NULL, 
    RESP_TYPE VARCHAR2(1) DEFAULT 'R' NOT NULL, 
    USER_ID NUMBER, 
    L_LAST_NAME VARCHAR2(50), 
    L_FIRST_NAME VARCHAR2(50), 
    L_DEPARTMENT VARCHAR2(30), 
    ALIAS_NAME VARCHAR2(255) NOT NULL, 
    DELETED_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL, 
    CREATED_USER VARCHAR2(30) NOT NULL, 
    CREATED_DATE TIMESTAMP (6) NOT NULL, 
    MODIFIED_USER VARCHAR2(30), 
    MODIFIED_DATE TIMESTAMP (6), 
    VERSION NUMBER NOT NULL ,
    
    CONSTRAINT T_PIDC_WP_RESP_PK PRIMARY KEY (A2L_RESP_ID),
     
    CONSTRAINT T_PIDC_WP_RESP_ALIAS_UK UNIQUE (PROJECT_ID, ALIAS_NAME, RESP_TYPE, USER_ID, L_LAST_NAME, L_FIRST_NAME), 
     
    CONSTRAINT T_PIDC_WP_RESP_USER_FK FOREIGN KEY (USER_ID)
       REFERENCES TABV_APIC_USERS (USER_ID), 
     
    CONSTRAINT T_PIDC_WP_RESP_PIDC_FK FOREIGN KEY (PROJECT_ID)
       REFERENCES TABV_PROJECTIDCARD (PROJECT_ID),
    
    CONSTRAINT T_A2L_RESPONSIBILITY_UK UNIQUE ( PROJECT_ID,ALIAS_NAME)
   );

COMMENT ON COLUMN T_A2L_RESPONSIBILITY.USER_ID IS 'iCDM User ID';
COMMENT ON COLUMN T_A2L_RESPONSIBILITY.ALIAS_NAME IS 'e.g. name from A2L GROUP';
COMMENT ON COLUMN T_A2L_RESPONSIBILITY.RESP_TYPE IS 'R- Robert Bosch, C- Customer, O- Other';


------------------------------------------------------------------------------------
--T_A2L_WORK_PACKAGES
------------------------------------------------------------------------------------
CREATE TABLE T_A2L_WORK_PACKAGES 
   (    
    A2L_WP_ID NUMBER NOT NULL, 
    WP_NAME VARCHAR2(255) NOT NULL, 
    WP_DESC VARCHAR2(255), 
    WP_NAME_CUST VARCHAR2(255), 
    PIDC_VERS_ID NUMBER NOT NULL, 
    VERSION NUMBER NOT NULL, 
    CREATED_DATE TIMESTAMP (6) NOT NULL, 
    CREATED_USER VARCHAR2(20) NOT NULL, 
    MODIFIED_DATE TIMESTAMP (6), 
    MODIFIED_USER VARCHAR2(20), 
    PARENT_A2L_WP_ID NUMBER, 
    
    CONSTRAINT T_A2L_WP_PAL_PK PRIMARY KEY (A2L_WP_ID), 
     
    CONSTRAINT T_A2L_WP_NAME_UK UNIQUE (WP_NAME, PIDC_VERS_ID), 
     
    CONSTRAINT T_A2L_WP_PIDC_VERS_FK FOREIGN KEY (PIDC_VERS_ID)
       REFERENCES T_PIDC_VERSION (PIDC_VERS_ID), 
     
    CONSTRAINT T_A2L_WP_PAL_PARENT_FK FOREIGN KEY (PARENT_A2L_WP_ID)
       REFERENCES T_A2L_WORK_PACKAGES (A2L_WP_ID)
   ) ;


------------------------------------------------------------------------------------
--T_A2L_WP_DEFN_VERSIONS
------------------------------------------------------------------------------------
CREATE TABLE T_A2L_WP_DEFN_VERSIONS 
   (    
    WP_DEFN_VERS_ID NUMBER(15,0) NOT NULL, 
    VERSION_NUMBER NUMBER(10,0) NOT NULL, 
    VERSION_NAME VARCHAR2(50) NOT NULL, 
    VERSION_DESC VARCHAR2(4000), 
    IS_ACTIVE VARCHAR2(1) NOT NULL, 
    PIDC_A2L_ID NUMBER(15,0) NOT NULL, 
    PARAM_LVL_CHG_ALLOWD_FLAG VARCHAR2(1) NOT NULL,
    VCDM_PVD_ID NUMBER, 
    VCDM_PRD_ID NUMBER,
    CREATED_DATE TIMESTAMP (6) NOT NULL, 
    CREATED_USER VARCHAR2(30) NOT NULL, 
    MODIFIED_DATE TIMESTAMP (6), 
    MODIFIED_USER VARCHAR2(30), 
    VERSION NUMBER(15,0) NOT NULL, 
    
    CONSTRAINT T_A2L_WP_DEFINITION_VERSION_PK PRIMARY KEY (WP_DEFN_VERS_ID), 
    
    CONSTRAINT T_A2L_WP_DEFINITION_VERSI_UK1 UNIQUE (VERSION_NUMBER, PIDC_A2L_ID), 
    
    CONSTRAINT T_PIDC_A2L_FK FOREIGN KEY (PIDC_A2L_ID)
       REFERENCES T_PIDC_A2L (PIDC_A2L_ID)
   ) ;
   
   COMMENT ON COLUMN T_A2L_WP_DEFN_VERSIONS.VCDM_PVD_ID IS 'vCDM VERSION_NUMBER of PVD for default varGrp';
   COMMENT ON COLUMN T_A2L_WP_DEFN_VERSIONS.VCDM_PRD_ID IS 'vCDM VERSION_NUMBER of PRD for default varGrp';


------------------------------------------------------------------------------------
--T_A2L_VARIANT_GROUPS
------------------------------------------------------------------------------------
CREATE TABLE T_A2L_VARIANT_GROUPS 
   (    
    A2L_VAR_GRP_ID NUMBER(15,0) NOT NULL, 
    GROUP_NAME VARCHAR2(50) NOT NULL, 
    GROUP_DESC VARCHAR2(100), 
    WP_DEFN_VERS_ID NUMBER(15,0) NOT NULL, 
    CREATED_DATE TIMESTAMP (6) NOT NULL, 
    CREATED_USER VARCHAR2(30) NOT NULL, 
    MODIFIED_DATE TIMESTAMP (6), 
    MODIFIED_USER VARCHAR2(30), 
    VERSION NUMBER(10,0) NOT NULL, 
    
    CONSTRAINT T_A2L_VARIANT_GROUP_PK PRIMARY KEY (A2L_VAR_GRP_ID), 
    
    CONSTRAINT T_A2L_VARIANT_GROUP__UN UNIQUE (WP_DEFN_VERS_ID, GROUP_NAME), 
    
    CONSTRAINT T_A2L_VAR_GRP_WP_DEFN_VERS_FK FOREIGN KEY (WP_DEFN_VERS_ID)
       REFERENCES T_A2L_WP_DEFN_VERSIONS (WP_DEFN_VERS_ID)
   ) ;


------------------------------------------------------------------------------------
--T_A2L_VARGRP_VARIANT_MAPPING
------------------------------------------------------------------------------------
CREATE TABLE T_A2L_VARGRP_VARIANT_MAPPING 
   (
    VARGRP_VAR_MAP_ID NUMBER(15,0) NOT NULL, 
    A2L_VAR_GRP_ID NUMBER(15,0) NOT NULL, 
    VARIANT_ID NUMBER(15,0) NOT NULL, 
    CREATED_DATE TIMESTAMP (6) NOT NULL, 
    CREATED_USER VARCHAR2(30) NOT NULL, 
    MODIFIED_DATE TIMESTAMP (6), 
    MODIFIED_USER VARCHAR2(30), 
    VERSION NUMBER(10,0) NOT NULL, 
    
    CONSTRAINT T_A2L_VAR_GRP_VAR_MAPPING_PK PRIMARY KEY (VARGRP_VAR_MAP_ID), 
    
    CONSTRAINT T_A2L_VAR_GRP_VAR_MAPPING__UN UNIQUE (A2L_VAR_GRP_ID, VARIANT_ID), 
    
    CONSTRAINT T_A2L_PROJECT_VARIANTS_FK FOREIGN KEY (VARIANT_ID)
       REFERENCES TABV_PROJECT_VARIANTS (VARIANT_ID), 
    
    CONSTRAINT T_A2L_VARIANT_GROUP_MAP_FK FOREIGN KEY (A2L_VAR_GRP_ID)
       REFERENCES T_A2L_VARIANT_GROUPS (A2L_VAR_GRP_ID)
   ) ;


------------------------------------------------------------------------------------
--T_A2L_WP_RESPONSIBILITY
------------------------------------------------------------------------------------   
CREATE TABLE T_A2L_WP_RESPONSIBILITY 
   (    
    WP_RESP_ID NUMBER(15,0) NOT NULL, 
    WP_DEFN_VERS_ID NUMBER(15,0) NOT NULL, 
    A2L_RESP_ID NUMBER(15,0) NOT NULL, 
    A2L_VAR_GRP_ID NUMBER(15,0), 
    A2L_WP_ID NUMBER NOT NULL,
    CREATED_DATE TIMESTAMP (6) NOT NULL, 
    CREATED_USER VARCHAR2(30) NOT NULL, 
    MODIFIED_DATE TIMESTAMP (6), 
    MODIFIED_USER VARCHAR2(30), 
    VERSION NUMBER(10,0) NOT NULL, 
    
    CONSTRAINT T_A2L_WP_RESP_PK PRIMARY KEY (WP_RESP_ID), 
    
    CONSTRAINT T_A2L_WP_RESP__UN UNIQUE (WP_DEFN_VERS_ID, A2L_VAR_GRP_ID, A2L_WP_ID), 
    
    CONSTRAINT T_A2L_WP_RESP_WP_DEFN_VERS_FK FOREIGN KEY (WP_DEFN_VERS_ID)
        REFERENCES T_A2L_WP_DEFN_VERSIONS (WP_DEFN_VERS_ID), 
    
    CONSTRAINT FK_WP_RESP_PAL_PIDC_RESP FOREIGN KEY (A2L_RESP_ID)
        REFERENCES T_A2L_RESPONSIBILITY (A2L_RESP_ID), 
     
    CONSTRAINT FK_WP_RESP_PAL_VAR_GRP FOREIGN KEY (A2L_VAR_GRP_ID)
        REFERENCES T_A2L_VARIANT_GROUPS (A2L_VAR_GRP_ID), 
     
    CONSTRAINT FK_A2L_WP_PAL FOREIGN KEY (A2L_WP_ID)
        REFERENCES T_A2L_WORK_PACKAGES (A2L_WP_ID)
   );


------------------------------------------------------------------------------------
--T_A2L_WP_PARAM_MAPPING
------------------------------------------------------------------------------------
CREATE TABLE T_A2L_WP_PARAM_MAPPING
   (    
    WP_PARAM_MAP_ID NUMBER(15,0) NOT NULL, 
    PARAM_ID NUMBER(15,0) NOT NULL, 
    WP_RESP_ID NUMBER(15,0) NOT NULL, 
    WP_NAME_CUST_INHERIT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL, 
    WP_NAME_CUST VARCHAR2(130), 
    WP_RESP_INHERIT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL, 
    PAR_A2L_RESP_ID NUMBER(15,0), 
    CREATED_DATE TIMESTAMP (6) NOT NULL, 
    CREATED_USER VARCHAR2(30) NOT NULL, 
    MODIFIED_DATE TIMESTAMP (6), 
    MODIFIED_USER VARCHAR2(30), 
    VERSION NUMBER(10,0) NOT NULL, 
    
    CONSTRAINT T_A2L_WP_PARAM_MAPPING_PK PRIMARY KEY (WP_PARAM_MAP_ID), 
    
    CONSTRAINT T_A2L_WP_PARAM_MAPPING__UN UNIQUE (PARAM_ID, WP_RESP_ID), 
    
    CONSTRAINT T_A2L_WP_PARAM_PARAMETER_FK FOREIGN KEY (PARAM_ID)
       REFERENCES T_PARAMETER (ID), 
    
    CONSTRAINT T_A2L_WP_PARAM_WP_RESP_FK FOREIGN KEY (WP_RESP_ID)
       REFERENCES T_A2L_WP_RESPONSIBILITY (WP_RESP_ID), 
    
    CONSTRAINT FK_PARAM_MAP_PIDC_RESP FOREIGN KEY (PAR_A2L_RESP_ID)
       REFERENCES T_A2L_RESPONSIBILITY (A2L_RESP_ID)
   ) ;

CREATE INDEX T_A2L_WP_PARAM_MAP_IDX_RESP_ID ON T_A2L_WP_PARAM_MAPPING (WP_RESP_ID);


------------------------------------------------------------------------------------
--T_RVW_WP_RESP
------------------------------------------------------------------------------------
CREATE TABLE T_RVW_WP_RESP 
   (    
    RVW_WP_RESP_ID NUMBER NOT NULL, 
    RESULT_ID NUMBER NOT NULL, 
    A2L_WP_ID NUMBER NOT NULL, 
    A2L_RESP_ID NUMBER NOT NULL, 
    CREATED_DATE TIMESTAMP (6) NOT NULL, 
    CREATED_USER VARCHAR2(30) NOT NULL, 
    MODIFIED_DATE TIMESTAMP (6), 
    MODIFIED_USER VARCHAR2(30), 
    VERSION NUMBER NOT NULL, 
    
    CONSTRAINT RVW_WP_RESP_PK PRIMARY KEY (RVW_WP_RESP_ID), 
    
    CONSTRAINT RVW_WP_RESP_FK2 FOREIGN KEY (RESULT_ID)
        REFERENCES T_RVW_RESULTS (RESULT_ID), 
    
    CONSTRAINT RVW_WP_RESP_FK3 FOREIGN KEY (A2L_RESP_ID)
        REFERENCES T_A2L_RESPONSIBILITY (A2L_RESP_ID), 
    
    CONSTRAINT RVW_WP_RESP_FK1 FOREIGN KEY (A2L_WP_ID)
        REFERENCES T_A2L_WORK_PACKAGES (A2L_WP_ID)
   ) ;


------------------------------------------------------------------------------------
--T_PIDC_A2L
------------------------------------------------------------------------------------
ALTER TABLE T_PIDC_A2L ADD
   ( 
    WP_PARAM_PRESENT_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL, 
    ACTIVE_WP_PARAM_PRESENT_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL, 
    IS_WORKING_SET_MODIFIED VARCHAR2(1) DEFAULT 'N' NOT NULL
   );

   
------------------------------------------------------------------------------------
--T_RVW_RESULTS
------------------------------------------------------------------------------------
ALTER TABLE T_RVW_RESULTS ADD
   ( 
    WP_DEFN_VERS_ID NUMBER(15,0), 
    
    CONSTRAINT T_RVW_RESULTS_WP_DEFN_VERS_FK FOREIGN KEY (WP_DEFN_VERS_ID)
        REFERENCES T_A2L_WP_DEFN_VERSIONS (WP_DEFN_VERS_ID)
   );
   
------------------------------------------------------------------------------------
--T_RVW_PARAMETERS
------------------------------------------------------------------------------------
ALTER TABLE T_RVW_PARAMETERS ADD
   (      
    RVW_WP_RESP_ID NUMBER, 
    
    CONSTRAINT T_RVW_PARAMETERS_FK6 FOREIGN KEY (RVW_WP_RESP_ID)
        REFERENCES T_RVW_WP_RESP (RVW_WP_RESP_ID)  
   );

spool off
