spool c:\temp\01_Table_Alters.log

---------------------------------------------------------------------
--  ALM TaskId : 263187: Create database scripts for Risk Evaluation
--  DDL for Table T_RM_PROJECT_CHARACTER
---------------------------------------------------------------------

  CREATE TABLE T_RM_PROJECT_CHARACTER 
   (    PRJ_CHARACTER_ID NUMBER NOT NULL ENABLE, 
    PARENT_PRJ_CHARACTER_ID NUMBER, 
    PROJECT_CHARACTER_ENG VARCHAR2(2000 BYTE), 
    PROJECT_CHARACTER_GER VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
    DELETED_FLAG VARCHAR2(1 BYTE), 
    CREATED_USER VARCHAR2(30 BYTE) NOT NULL ENABLE, 
    MODIFIED_USER VARCHAR2(30 BYTE), 
    CREATED_DATE TIMESTAMP (6) NOT NULL ENABLE, 
    MODIFIED_DATE TIMESTAMP (6), 
    VERSION NUMBER NOT NULL ENABLE, 
  
     CONSTRAINT T_RM_PROJECT_CHARACTER_PK PRIMARY KEY (PRJ_CHARACTER_ID), 
     CONSTRAINT T_RM_PROJECT_CHARACTER_UK UNIQUE (PROJECT_CHARACTER_ENG), 
     CONSTRAINT T_RM_PC_PARENT_FK FOREIGN KEY (PARENT_PRJ_CHARACTER_ID)  REFERENCES T_RM_PROJECT_CHARACTER (PRJ_CHARACTER_ID) 
   )  ;
   
--------------------------------------------------------
--  DDL for Table T_RM_RISK_LEVEL
--------------------------------------------------------

  CREATE TABLE T_RM_RISK_LEVEL 
   (    RISK_LEVEL_ID NUMBER NOT NULL ENABLE, 
    RISK_TEXT_ENG VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    RISK_TEXT_GER VARCHAR2(100 BYTE), 
    RISK_DESC_ENG VARCHAR2(2000 BYTE), 
    RISK_DESC_GER VARCHAR2(2000 BYTE), 
    RISK_WEIGHT NUMBER(1,0), 
    CREATED_USER VARCHAR2(30 BYTE) NOT NULL ENABLE, 
    MODIFIED_USER VARCHAR2(30 BYTE), 
    CREATED_DATE TIMESTAMP (6) NOT NULL ENABLE, 
    MODIFIED_DATE TIMESTAMP (6), 
    VERSION NUMBER NOT NULL ENABLE, 
  
     CONSTRAINT T_RM_RISK_LEVEL_PK PRIMARY KEY (RISK_LEVEL_ID), 
     CONSTRAINT T_RM_RISK_LEVEL_UK UNIQUE (RISK_TEXT_ENG)
   )  ;
  
--------------------------------------------------------
--  DDL for Table T_RM_CATEGORY
--------------------------------------------------------

  CREATE TABLE T_RM_CATEGORY 
   (    CATEGORY_ID NUMBER NOT NULL ENABLE, 
    CATEGORY_ENG VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    CATEGORY_GER VARCHAR2(100 BYTE), 
    CREATED_USER VARCHAR2(30 BYTE) NOT NULL ENABLE, 
    MODIFIED_USER VARCHAR2(30 BYTE), 
    CREATED_DATE TIMESTAMP (6) NOT NULL ENABLE, 
    MODIFIED_DATE TIMESTAMP (6), 
    VERSION NUMBER NOT NULL ENABLE, 
    CAT_TYPE VARCHAR2(1 BYTE), 
  
     CONSTRAINT T_RM_CATEGORY_PK PRIMARY KEY (CATEGORY_ID), 
     CONSTRAINT T_RM_CATEGORY_UK UNIQUE (CATEGORY_ENG)
   ) ;

--------------------------------------------------------
--  DDL for Table T_RM_CATEGORY_MEASURES
--------------------------------------------------------

  CREATE TABLE T_RM_CATEGORY_MEASURES 
   (    CATEGORY_MEASURE_ID NUMBER NOT NULL ENABLE, 
    CATEGORY_ID NUMBER NOT NULL ENABLE, 
    RISK_LEVEL_ID NUMBER NOT NULL ENABLE, 
    MEASURE_ENG VARCHAR2(4000 BYTE), 
    MEASURE_GER VARCHAR2(4000 BYTE), 
    CREATED_USER VARCHAR2(30 BYTE) NOT NULL ENABLE, 
    MODIFIED_USER VARCHAR2(30 BYTE), 
    CREATED_DATE TIMESTAMP (6) NOT NULL ENABLE, 
    MODIFIED_DATE TIMESTAMP (6), 
    VERSION NUMBER NOT NULL ENABLE, 
  
     CONSTRAINT T_RM_CATEGORY_MEASURES_PK PRIMARY KEY (CATEGORY_MEASURE_ID), 
     CONSTRAINT T_RM_CATEGORY_MEASURES_UK1 UNIQUE (CATEGORY_ID, RISK_LEVEL_ID), 
     CONSTRAINT T_RM_CAT_ME_RISK_LEVEL_FK FOREIGN KEY (RISK_LEVEL_ID)  REFERENCES T_RM_RISK_LEVEL (RISK_LEVEL_ID), 
     CONSTRAINT T_RM_CAT_MEASURES_FK FOREIGN KEY (CATEGORY_ID) REFERENCES T_RM_CATEGORY (CATEGORY_ID)
   )  ;

     
--------------------------------------------------------
--  DDL for Table T_RM_CHARACTER_CATEGORY_MATRIX
--------------------------------------------------------

  CREATE TABLE T_RM_CHARACTER_CATEGORY_MATRIX 
   (    CCM_ID NUMBER NOT NULL ENABLE, 
    PRJ_CHARACTER_ID NUMBER NOT NULL ENABLE, 
    CATEGORY_ID NUMBER NOT NULL ENABLE, 
    RISK_LEVEL_ID NUMBER NOT NULL ENABLE, 
    CREATED_USER VARCHAR2(30 BYTE) NOT NULL ENABLE, 
    MODIFIED_USER VARCHAR2(30 BYTE), 
    CREATED_DATE TIMESTAMP (6) NOT NULL ENABLE, 
    MODIFIED_DATE TIMESTAMP (6), 
    VERSION NUMBER NOT NULL ENABLE, 
  
     CONSTRAINT T_RM_CCM_PK PRIMARY KEY (CCM_ID), 
     CONSTRAINT T_RM_CHARACTER_CATEGORY_M_UK1 UNIQUE (PRJ_CHARACTER_ID, CATEGORY_ID), 
     CONSTRAINT T_RM_MATRIX_CATEGORY_FK FOREIGN KEY (CATEGORY_ID)  REFERENCES T_RM_CATEGORY (CATEGORY_ID) , 
     CONSTRAINT T_RM_MATRIX_CHARACTER_FK FOREIGN KEY (PRJ_CHARACTER_ID)  REFERENCES T_RM_PROJECT_CHARACTER (PRJ_CHARACTER_ID) , 
     CONSTRAINT T_RM_MATRIX_RISK_LEVEL_FK FOREIGN KEY (RISK_LEVEL_ID)  REFERENCES T_RM_RISK_LEVEL (RISK_LEVEL_ID) 
   ) ;
   
   
--------------------------------------------------------
--  DDL for Table T_PIDC_RM_DEFINITION
--------------------------------------------------------
  CREATE TABLE T_PIDC_RM_DEFINITION 
   (    PIDC_RM_ID NUMBER NOT NULL ENABLE, 
    PIDC_VERS_ID NUMBER(15,0) NOT NULL ENABLE, 
    RM_NAME_ENG VARCHAR2(200 BYTE) NOT NULL ENABLE, 
    RM_NAME_GER VARCHAR2(200 BYTE), 
    RM_DESC_ENG VARCHAR2(2000 BYTE), 
    RM_DESC_GER VARCHAR2(2000 BYTE), 
    IS_VARIANT VARCHAR2(1 BYTE), 
    CREATED_USER VARCHAR2(30 BYTE) NOT NULL ENABLE, 
    MODIFIED_USER VARCHAR2(30 BYTE), 
    CREATED_DATE TIMESTAMP (6) NOT NULL ENABLE, 
    MODIFIED_DATE TIMESTAMP (6), 
    VERSION NUMBER NOT NULL ENABLE,
  
   CONSTRAINT T_RM_PIDC_PK PRIMARY KEY (PIDC_RM_ID), 
     CONSTRAINT T_PIDC_RM_DEFINITION_UK1 UNIQUE (PIDC_VERS_ID, RM_NAME_ENG), 
     CONSTRAINT T_RM_PIDC_T_PIDC_VERSION_FK FOREIGN KEY (PIDC_VERS_ID) REFERENCES T_PIDC_VERSION (PIDC_VERS_ID)
   );

--------------------------------------------------------
--  DDL for Table T_PIDC_RM_PROJECT_CHARACTER
--------------------------------------------------------

  CREATE TABLE T_PIDC_RM_PROJECT_CHARACTER 
   (    PIDC_PC_ID NUMBER NOT NULL ENABLE, 
    PIDC_RM_ID NUMBER NOT NULL ENABLE, 
    PRJ_CHARACTER_ID NUMBER NOT NULL ENABLE, 
    RELEVANT_FLAG VARCHAR2(1 BYTE), 
    RB_SHARE NUMBER NOT NULL ENABLE, 
    RB_DATA NUMBER NOT NULL ENABLE, 
    CREATED_USER VARCHAR2(30 BYTE) NOT NULL ENABLE, 
    MODIFIED_USER VARCHAR2(30 BYTE), 
    CREATED_DATE TIMESTAMP (6) NOT NULL ENABLE, 
    MODIFIED_DATE TIMESTAMP (6), 
    VERSION NUMBER NOT NULL ENABLE,
  
    CONSTRAINT T_RM_PIDC_EVALUATION_PK PRIMARY KEY (PIDC_PC_ID),
     CONSTRAINT T_RM_PIDC_EVALUATION_UK UNIQUE (PIDC_RM_ID, PRJ_CHARACTER_ID), 
     CONSTRAINT T_RM_EVALUATION_CHARACTER_FK FOREIGN KEY (PRJ_CHARACTER_ID)  REFERENCES T_RM_PROJECT_CHARACTER (PRJ_CHARACTER_ID), 
     CONSTRAINT T_RM_EVALUATION_PIDC_FK FOREIGN KEY (PIDC_RM_ID)    REFERENCES T_PIDC_RM_DEFINITION (PIDC_RM_ID), 
     CONSTRAINT T_RM_PC_CATEGORY_INPUT_DATA_FK FOREIGN KEY (RB_DATA)  REFERENCES T_RM_CATEGORY (CATEGORY_ID) , 
     CONSTRAINT T_RM_PC_CATEGORY_SHARE_FK FOREIGN KEY (RB_SHARE)  REFERENCES T_RM_CATEGORY (CATEGORY_ID)   
   )  ;

---------------------------------------------------------------------
--  ALM TaskId : 263187: Create database scripts for Risk Evaluation
--  Alter Query for TABV_PROJECT_VARIANTS, TABV_PROJECT_SUB_VARIANTS
---------------------------------------------------------------------  
  
  ALTER TABLE TABV_PROJECT_VARIANTS ADD (PIDC_RM_ID  NUMBER);
  ALTER TABLE TABV_PROJECT_VARIANTS ADD CONSTRAINT TABV_PROJ_VAR_FK_RM foreign key(PIDC_RM_ID) references T_PIDC_RM_DEFINITION(PIDC_RM_ID);
  
  ALTER TABLE TABV_PROJECT_SUB_VARIANTS ADD (PIDC_RM_ID  NUMBER);  
  ALTER TABLE TABV_PROJECT_SUB_VARIANTS ADD CONSTRAINT TABV_PROJ_SUB_VAR_FK_RM foreign key(PIDC_RM_ID) references T_PIDC_RM_DEFINITION(PIDC_RM_ID);

spool off