spool c:\temp\50_grants.log

--  ALM TaskId : 263187: Create database scripts for Risk Evaluation
--  Grants for Risk Evaluation tables to DGS_ICDM_DEV_JPA user

GRANT DELETE, INSERT, SELECT, UPDATE ON T_RM_PROJECT_CHARACTER TO DGS_ICDM_JPA;
GRANT DELETE, INSERT, SELECT, UPDATE ON T_RM_RISK_LEVEL TO DGS_ICDM_JPA;
GRANT DELETE, INSERT, SELECT, UPDATE ON T_RM_CATEGORY TO DGS_ICDM_JPA;
GRANT DELETE, INSERT, SELECT, UPDATE ON T_RM_CATEGORY_MEASURES TO DGS_ICDM_JPA;
GRANT DELETE, INSERT, SELECT, UPDATE ON T_RM_CHARACTER_CATEGORY_MATRIX TO DGS_ICDM_JPA;
GRANT DELETE, INSERT, SELECT, UPDATE ON T_PIDC_RM_DEFINITION TO DGS_ICDM_JPA;
GRANT DELETE, INSERT, SELECT, UPDATE ON T_PIDC_RM_PROJECT_CHARACTER TO DGS_ICDM_JPA;

spool off
