   
CREATE MATERIALIZED VIEW MV_TABE_DATASETS 
USING INDEX 
REFRESH START WITH GREATEST(SYSDATE,TO_DATE('2013.03.18.16.29.22','YYYY.MM.DD.HH24.MI.SS')) NEXT SYSDATE + (1/(24*60)) FAST 
WITH PRIMARY KEY 
DISABLE QUERY REWRITE AS 
SELECT *
FROM TABE_DATASETS@DGSPRO.WORLD@K5ESK_VILLA_RO
;

CREATE MATERIALIZED VIEW MV_TA2L_FILEINFO 
USING INDEX 
REFRESH START WITH GREATEST(SYSDATE,TO_DATE('2013.03.18.16.29.22','YYYY.MM.DD.HH24.MI.SS')) NEXT SYSDATE + (1/(24*60)) FAST 
WITH PRIMARY KEY 
DISABLE QUERY REWRITE AS 
SELECT *
FROM TA2L_FILEINFO@DGSPRO.WORLD@K5ESK_VILLA_RO
;

CREATE MATERIALIZED VIEW MV_TABV_CALDATAFILES 
USING INDEX 
REFRESH START WITH GREATEST(SYSDATE,TO_DATE('2013.03.18.16.29.22','YYYY.MM.DD.HH24.MI.SS')) NEXT SYSDATE + (1/(24*60)) FAST 
WITH PRIMARY KEY 
DISABLE QUERY REWRITE AS 
SELECT *
FROM TABV_CALDATAFILES@DGSPRO.WORLD@K5ESK_VILLA_RO
;

alter table "DGS_ICDM"."MV_TABV_CALDATAFILES" 
  add constraint FK_CALDATAFILES_EASEEDST foreign key("EASEEDST_ID") references "MV_TABE_DATASETS"("EASEEDST_ID")
;

alter table "DGS_ICDM"."MV_TABV_CALDATAFILES" 
  add constraint FK_CALDATAFILES_A2LFILEINFO foreign key("A2L_INFO_ID") references "MV_TA2L_FILEINFO"("ID")
;

--
--
--
CREATE MATERIALIZED VIEW MV_SDOM_SYSCON 
USING INDEX 
REFRESH ON DEMAND COMPLETE 
DISABLE QUERY REWRITE AS 
SELECT *
FROM RB_CCE_V_CUR_SYSKON_VERSIONS@SCMPRO.WORLD@HEF2FE_RO
;

alter table "DGS_ICDM"."MV_SDOM_SYSCON" add constraint PK_SDOM_SYSCON primary key("SYSKON_NUMMER")
;

CREATE MATERIALIZED VIEW MV_SDOM_SYSCON_VALUES 
USING INDEX 
REFRESH ON DEMAND COMPLETE 
DISABLE QUERY REWRITE AS 
SELECT *
FROM RB_CCE_V_CUR_SYSKON_LEGAL_VAL@SCMPRO.WORLD@HEF2FE_RO
;

alter table "DGS_ICDM"."MV_SDOM_SYSCON_VALUES" add constraint PK_SDOM_SYSCON_VALUES primary key("SYSKON_WERT_ID")
;

alter table MV_SDOM_SYSCON_VALUES 
  add constraint FK_SYSCONVAL_SYSCON foreign key(SYSKON_NUMMER) references MV_SDOM_SYSCON(SYSKON_NUMMER)
;



GRANT select on MV_TABE_DATASETS to DGS_ICDM_JPA;
GRANT select on MV_TA2L_FILEINFO to DGS_ICDM_JPA;
GRANT select on MV_TABV_CALDATAFILES to DGS_ICDM_JPA;
GRANT select on MV_SDOM_SYSCON to DGS_ICDM_JPA;
GRANT select on MV_SDOM_SYSCON_VALUES to DGS_ICDM_JPA;

CREATE SYNONYM MV_TABE_DATASETS for DGS_ICDM.MV_TABE_DATASETS;
CREATE SYNONYM MV_TA2L_FILEINFO for DGS_ICDM.MV_TA2L_FILEINFO;
CREATE SYNONYM MV_TABV_CALDATAFILES for DGS_ICDM.MV_TABV_CALDATAFILES;
CREATE SYNONYM MV_SDOM_SYSCON for DGS_ICDM.MV_SDOM_SYSCON;
CREATE SYNONYM MV_SDOM_SYSCON_VALUES for DGS_ICDM.MV_SDOM_SYSCON_VALUES;
