alter table "DGS_ICDM"."MV_TABV_CALDATAFILES" 
  drop constraint FK_CALDATAFILES_EASEEDST
;

alter table "DGS_ICDM"."MV_TABV_CALDATAFILES" 
  drop constraint FK_CALDATAFILES_A2LFILEINFO
;

DROP MATERIALIZED VIEW MV_TABE_DATASETS;
DROP MATERIALIZED VIEW MV_TA2L_FILEINFO;
DROP MATERIALIZED VIEW MV_TABV_CALDATAFILES;
