spool c:\temp\table_updates.log

--
-- SeqV_Attributes
--
ALTER SEQUENCE SEQV_ATTRIBUTES INCREMENT BY 50 CACHE 5;

--
-- TABV_PID_HISTORY
--
-- remove modify date/user columns
-- add single primary key column PIDHIST_ID
-- create unique contraint for Project_ID, Pro_Rev_ID, PID_Status_ID
--
ALTER TABLE TABV_PID_HISTORY 
DROP CONSTRAINT TABV_PID_HISTORY_PK;

DROP INDEX TABV_PID_HISTORY_PK;

ALTER TABLE TABV_PID_HISTORY 
DROP COLUMN MODIFIED_DATE;

ALTER TABLE TABV_PID_HISTORY 
DROP COLUMN MODIFIED_USER;

ALTER TABLE TABV_PID_HISTORY 
ADD (PIDHIST_ID NUMBER);

UPDATE tabv_pid_history
  set pidhist_id = seqv_Attributes.NextVal;

ALTER TABLE TABV_PID_HISTORY
ADD CONSTRAINT TABV_PID_HISTORY_PK PRIMARY KEY 
(
  PIDHIST_ID 
)
ENABLE;

ALTER TABLE TABV_PID_HISTORY
ADD CONSTRAINT TABV_PID_HISTORY_UK1 UNIQUE 
(
  PROJECT_ID 
, PRO_REV_ID 
, PID_STATUS_ID 
)
ENABLE;

--
-- NEW table TABV_APIC_USER
--
CREATE TABLE TABV_APIC_USERS 
(
  USER_ID NUMBER NOT NULL 
, USERNAME VARCHAR2(30) NOT NULL 
, FIRSTNAME VARCHAR2(50) 
, LASTNAME VARCHAR2(50) 
, DEPARTMENT VARCHAR2(50) 
, VERSION NUMBER NOT NULL
, CREATED_USER VARCHAR2(30) NOT NULL 
, CREATED_DATE TIMESTAMP NOT NULL 
, MODIFIED_USER VARCHAR2(30) 
, MODIFIED_DATE TIMESTAMP 
, CONSTRAINT PK_APIC_USERS PRIMARY KEY 
  (
    USER_ID 
  )
  ENABLE 
);

ALTER TABLE TABV_APIC_USERS
ADD CONSTRAINT TABV_APIC_USERS_UK1 UNIQUE 
(
  USERNAME 
)
ENABLE;

insert into TABV_APIC_USERS
(User_ID, UserName, Created_User, Created_Date, version)
select seqv_attributes.nextval, UserName, user, sysdate, 1
from (select distinct (UserName)
        from TabV_Apic_Access_Rights
	 )	
;

--
-- TABV_APIC_ACCESS_RIGHTS
--
-- remove revoked column
-- add single primary key column ACCESSRIGHT_ID
-- create unique contraint for UserName, Module_Name
-- rename CRE_USER, CRE_DATE, MOD_USER, MOD_DATE
-- change datatype of CRE/MOD_DATE to TIMESTAMP
-- add VERSION column
--
ALTER TABLE TABV_APIC_ACCESS_RIGHTS 
DROP CONSTRAINT TABV_APIC_ACCESS_RIGHTS_PK;

DROP INDEX TABV_APIC_ACCESS_RIGHTS_PK;

ALTER TABLE TABV_APIC_ACCESS_RIGHTS 
DROP COLUMN ACCR_ID;

ALTER TABLE TABV_APIC_ACCESS_RIGHTS 
DROP COLUMN REVOKED;

ALTER TABLE TABV_APIC_ACCESS_RIGHTS 
ADD (ACCESSRIGHT_ID NUMBER);

UPDATE TABV_APIC_ACCESS_RIGHTS
  set ACCESSRIGHT_ID = seqv_Attributes.NextVal;

ALTER TABLE TABV_APIC_ACCESS_RIGHTS
ADD CONSTRAINT TABV_APIC_ACCESS_RIGHTS_PK PRIMARY KEY 
(
  ACCESSRIGHT_ID 
)
ENABLE;

ALTER TABLE TABV_APIC_ACCESS_RIGHTS 
	RENAME COLUMN CRE_USER TO CREATED_USER;

ALTER TABLE TABV_APIC_ACCESS_RIGHTS 
	RENAME COLUMN CRE_DATE TO CREATED_DATE;

ALTER TABLE TABV_APIC_ACCESS_RIGHTS 
	RENAME COLUMN MOD_USER TO MODIFIED_USER;

ALTER TABLE TABV_APIC_ACCESS_RIGHTS 
	RENAME COLUMN MOD_DATE TO MODIFIED_DATE;

ALTER TABLE TABV_APIC_ACCESS_RIGHTS  
	MODIFY (CREATED_DATE TIMESTAMP );

ALTER TABLE TABV_APIC_ACCESS_RIGHTS  
	MODIFY (MODIFIED_DATE TIMESTAMP );

ALTER TABLE TABV_APIC_ACCESS_RIGHTS 
ADD (VERSION NUMBER);

UPDATE TABV_APIC_ACCESS_RIGHTS
	set VERSION = 1;

ALTER TABLE TABV_APIC_ACCESS_RIGHTS  
MODIFY (VERSION NOT NULL);

ALTER TABLE TABV_APIC_ACCESS_RIGHTS 
ADD (USER_ID NUMBER);

update TabV_Apic_Access_Rights t1
  set User_ID = (select User_ID from TabV_Apic_USERS where UserName = t1.UserName)
;

alter table TABV_APIC_ACCESS_RIGHTS 
  drop constraint TABV_APIC_ACCESS_RIGHTS_UK1
;

ALTER TABLE TABV_APIC_ACCESS_RIGHTS 
DROP COLUMN USERNAME
;

ALTER TABLE TABV_APIC_ACCESS_RIGHTS 
ADD CONSTRAINT TABV_APIC_ACCESS_RIGHTS_UK1 UNIQUE 
(
  User_ID
, Module_Name 
)
ENABLE;

alter table TABV_APIC_ACCESS_RIGHTS
  add constraint FK_ACCESS_RIGHT_APIC_USER foreign key(USER_ID) 
      references TABV_APIC_USERS(USER_ID)
;
	  

--
-- TABV_APIC_NODE_ACCESS
--
-- add single primary key column NODEACCESS_ID
-- create unique contraint for UserName, Node_ID
-- rename GRANTED_USER to CREATED_USER
-- create CREATED_DATE, MODIFIED_USER, MODIFIED_DATE
-- add VERSION column
--

DROP TRIGGER TRGV_TABV_APIC_NODE_ACCESS_UPD;

DROP TRIGGER TRGV_TABV_APIC_NODE_ACCESS_DEL;

ALTER TABLE TABV_APIC_NODE_ACCESS 
DROP CONSTRAINT TABV_APIC_NODE_ACCESS_PK;

DROP INDEX TABV_APIC_NODE_ACCESS_PK;

ALTER TABLE TABV_APIC_NODE_ACCESS 
ADD (NODEACCESS_ID NUMBER);

UPDATE TABV_APIC_NODE_ACCESS
  set NODEACCESS_ID = seqv_Attributes.NextVal;

ALTER TABLE TABV_APIC_NODE_ACCESS
ADD CONSTRAINT TABV_APIC_NODE_ACCESS_PK PRIMARY KEY 
(
  NODEACCESS_ID 
)
ENABLE;

ALTER TABLE TABV_APIC_NODE_ACCESS 
	RENAME COLUMN USER_NAME TO USERNAME;

ALTER TABLE TABV_APIC_NODE_ACCESS 
	RENAME COLUMN GRANTED_USER TO CREATED_USER;
	
ALTER TABLE TABV_APIC_NODE_ACCESS 
ADD (CREATED_DATE TIMESTAMP);

UPDATE TABV_APIC_NODE_ACCESS
	set CREATED_DATE = sysdate,
	    CREATED_USER = user
	;

ALTER TABLE TABV_APIC_NODE_ACCESS  
MODIFY (CREATED_DATE NOT NULL);

ALTER TABLE TABV_APIC_NODE_ACCESS 
ADD (MODIFIED_DATE TIMESTAMP);

ALTER TABLE TABV_APIC_NODE_ACCESS 
ADD (MODIFIED_USER VARCHAR2(30));

ALTER TABLE TABV_APIC_NODE_ACCESS 
ADD (NODE_TYPE VARCHAR2(15));

UPDATE TABV_APIC_NODE_ACCESS
	set NODE_TYPE = 'PIDC';

ALTER TABLE TABV_APIC_NODE_ACCESS  
MODIFY (NODE_TYPE NOT NULL);

ALTER TABLE TABV_APIC_NODE_ACCESS 
ADD (VERSION NUMBER);

UPDATE TABV_APIC_NODE_ACCESS
	set VERSION = 1;

ALTER TABLE TABV_APIC_NODE_ACCESS  
MODIFY (VERSION NOT NULL);
	
--	
update TABV_APIC_NODE_ACCESS 
  set username = upper(username)
;

ALTER TABLE TABV_APIC_NODE_ACCESS 
ADD (USER_ID NUMBER);

update TabV_APIC_NODE_ACCESS t1
  set User_ID = (select User_ID from TabV_Apic_USERS where UserName = t1.UserName)
;

ALTER TABLE TABV_APIC_NODE_ACCESS 
DROP COLUMN USERNAME
;

ALTER TABLE TABV_APIC_NODE_ACCESS 
ADD CONSTRAINT TABV_APIC_NODE_ACCESS_UK1 UNIQUE 
(
  User_ID
, Node_ID 
)
ENABLE;

alter table TABV_APIC_NODE_ACCESS
  add constraint FK_NODE_ACCESS_APIC_USER foreign key(USER_ID) 
      references TABV_APIC_USERS(USER_ID)
;
	
--
-- TABV_ATTRIBUTES
--
-- remove SINGLE_MULTIPLE_VAL
--
ALTER TABLE TABV_ATTRIBUTES
DROP COLUMN SINGLE_MULTIPLE_VAL
;

ALTER TABLE TABV_ATTRIBUTES 
ADD (VERSION NUMBER);

UPDATE TABV_ATTRIBUTES
	set VERSION = 1
	;

ALTER TABLE TABV_ATTRIBUTES  
MODIFY (VERSION NOT NULL);

ALTER TABLE TABV_ATTRIBUTES
 DROP CONSTRAINT TABV_ATTRIBUTES_ENG_UNI
;

ALTER TABLE TABV_ATTRIBUTES
 ADD CONSTRAINT UK_APIC_ATTR_NAME_ENG unique(ATTR_NAME_ENG) 
;

ALTER TABLE TABV_ATTRIBUTES
DROP COLUMN ATTR_REV_ID
;

--
-- TABV_ATTR_VALUES
--
-- remove UNIT
--
ALTER TABLE TABV_ATTR_VALUES
DROP COLUMN UNITS
;

ALTER TABLE TABV_ATTR_VALUES 
ADD (VERSION NUMBER);

UPDATE TABV_ATTR_VALUES
	set VERSION = 1
	;

ALTER TABLE TABV_ATTR_VALUES  
MODIFY (VERSION NOT NULL);

ALTER TABLE TABV_ATTR_VALUES
 add constraint UK_APIC_ATTR_VALUES unique(ATTR_ID, NUMVALUE, DATEVALUE, BOOLVALUE, TEXTVALUE_ENG) 
; 

--
-- TABV_ATTR_DEPENDENCIES
--
-- add CRE/MOD columns
-- add VERSION column
--
ALTER TABLE TABV_ATTR_DEPENDENCIES 
ADD (VERSION NUMBER);

ALTER TABLE TABV_ATTR_DEPENDENCIES 
ADD (CREATED_USER VARCHAR2(30));

ALTER TABLE TABV_ATTR_DEPENDENCIES 
ADD (CREATED_DATE TIMESTAMP);

UPDATE TABV_ATTR_DEPENDENCIES
	set CREATED_DATE = sysdate,
	    CREATED_USER = user,
		VERSION = 1
	;

ALTER TABLE TABV_ATTR_DEPENDENCIES  
MODIFY (VERSION NOT NULL);

ALTER TABLE TABV_ATTR_DEPENDENCIES  
MODIFY (CREATED_USER NOT NULL);

ALTER TABLE TABV_ATTR_DEPENDENCIES  
MODIFY (CREATED_DATE NOT NULL);

ALTER TABLE TABV_ATTR_DEPENDENCIES 
ADD (MODIFIED_DATE TIMESTAMP);

ALTER TABLE TABV_ATTR_DEPENDENCIES 
ADD (MODIFIED_USER VARCHAR2(30));

delete from TABV_ATTR_DEPENDENCIES 
  where DEPEN_ATTR_ID is null;

ALTER TABLE TABV_ATTR_DEPENDENCIES 
MODIFY (DEPEN_ATTR_ID NOT NULL);

ALTER TABLE TABV_ATTR_DEPENDENCIES 
 ADD CONSTRAINT UK_APIC_ATTR_DEP UNIQUE(ATTR_ID, VALUE_ID, DEPEN_ATTR_ID, DEPEN_VALUE_ID) 
;

--
-- TABV_ATTR_GROUPS
--
-- add VERSION column
--
ALTER TABLE TABV_ATTR_GROUPS 
ADD (VERSION NUMBER);

UPDATE TABV_ATTR_GROUPS
	set VERSION = 1
	;

ALTER TABLE TABV_ATTR_GROUPS  
MODIFY (VERSION NOT NULL);

ALTER TABLE TABV_ATTR_GROUPS drop constraint TABV_ATTR_GROUPS_ENG_UNI;

ALTER TABLE TABV_ATTR_GROUPS 
DROP COLUMN GROUP_REV_ID;

ALTER TABLE TABV_ATTR_GROUPS
 add constraint TABV_ATTR_GROUPS_ENG_UNI unique(GROUP_NAME_ENG, SUPER_GROUP_ID) 
;

--
-- TABV_ATTR_SUPER_GROUPS
--
-- add VERSION column
--
ALTER TABLE TABV_ATTR_SUPER_GROUPS 
ADD (VERSION NUMBER);

UPDATE TABV_ATTR_SUPER_GROUPS
	set VERSION = 1
	;

ALTER TABLE TABV_ATTR_SUPER_GROUPS  
MODIFY (VERSION NOT NULL);

ALTER TABLE TABV_ATTR_SUPER_GROUPS drop constraint TABV_ATTR_SUPER_GROUPS_ENG_UNI;

ALTER TABLE TABV_ATTR_SUPER_GROUPS 
DROP COLUMN SUPER_GROUP_REV_ID;

ALTER TABLE TABV_ATTR_SUPER_GROUPS
 add constraint TABV_ATTR_SUPER_GROUPS_ENG_UNI unique(SUPER_GROUP_NAME_ENG) 
;

--
-- TABV_PROJ_SUB_VARIANTS_ATTR
--
-- add CRE/MOD columns
-- add VERSION column
--
ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR 
ADD (VERSION NUMBER);

ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR 
ADD (CREATED_USER VARCHAR2(30));

ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR 
ADD (CREATED_DATE TIMESTAMP);

UPDATE TABV_PROJ_SUB_VARIANTS_ATTR
	set CREATED_DATE = sysdate,
	    CREATED_USER = user,
		VERSION = 1
	;

ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR  
MODIFY (VERSION NOT NULL);

ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR  
MODIFY (CREATED_USER NOT NULL);

ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR  
MODIFY (CREATED_DATE NOT NULL);

ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR 
ADD (MODIFIED_DATE TIMESTAMP);

ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR 
ADD (MODIFIED_USER VARCHAR2(30));

--
-- TABV_PROJECT_ATTR
--
-- add CRE/MOD columns
-- add VERSION column
--
ALTER TABLE TABV_PROJECT_ATTR 
ADD (VERSION NUMBER);

ALTER TABLE TABV_PROJECT_ATTR 
ADD (CREATED_USER VARCHAR2(30));

ALTER TABLE TABV_PROJECT_ATTR 
ADD (CREATED_DATE TIMESTAMP);

UPDATE TABV_PROJECT_ATTR
	set CREATED_DATE = sysdate,
	    CREATED_USER = user,
		VERSION = 1
	;

ALTER TABLE TABV_PROJECT_ATTR  
MODIFY (VERSION NOT NULL);

ALTER TABLE TABV_PROJECT_ATTR  
MODIFY (CREATED_USER NOT NULL);

ALTER TABLE TABV_PROJECT_ATTR  
MODIFY (CREATED_DATE NOT NULL);

ALTER TABLE TABV_PROJECT_ATTR 
ADD (MODIFIED_DATE TIMESTAMP);

ALTER TABLE TABV_PROJECT_ATTR 
ADD (MODIFIED_USER VARCHAR2(30));

update tabv_project_attr
  set used = 'Y'
where value_id is not null
  and used <> 'Y'
;


ALTER TABLE TABV_PROJECT_ATTR 
ADD (IS_VARIANT VARCHAR2(1) )
;

update TABV_PROJECT_ATTR
  set is_variant = 'N'
;

update TABV_PROJECT_ATTR t1
  set is_variant = 'Y'
      , used = 'Y'
  where exists (select 1 
                  from tabv_variants_attr 
                 where attr_id = t1.attr_id
                   and project_id = t1.project_id
                   and pro_rev_id = t1.pro_rev_id
                )   
;

insert into TABV_PROJECT_ATTR t1
(project_id, attr_id, pro_rev_id, is_Variant, used)
  select distinct project_id, attr_id, pro_rev_id, 'Y', 'Y'
    from tabv_variants_attr t1
   where not exists (select 1
                      from tabv_project_attr
                     where project_id = t1.project_id
                       and attr_id = t1.attr_id
                       and pro_rev_id = t1.pro_rev_id
                     )
;

ALTER TABLE TABV_PROJECT_ATTR  
MODIFY (IS_VARIANT NOT NULL)
;

--
-- TABV_PROJECT_SUB_VARIANTS
--
-- add VERSION column
--
ALTER TABLE TABV_PROJECT_SUB_VARIANTS 
ADD (VERSION NUMBER);

UPDATE TABV_PROJECT_SUB_VARIANTS
	set VERSION = 1
	;

ALTER TABLE TABV_PROJECT_SUB_VARIANTS  
MODIFY (VERSION NOT NULL);

--
-- TABV_PROJECT_VARIANTS
--
-- add VERSION column
--
ALTER TABLE TABV_PROJECT_VARIANTS 
ADD (VERSION NUMBER);

UPDATE TABV_PROJECT_VARIANTS
	set VERSION = 1
	;

ALTER TABLE TABV_PROJECT_VARIANTS  
MODIFY (VERSION NOT NULL);

--
-- TABV_PROJECTIDCARD
--
-- add VERSION column
--
ALTER TABLE TABV_PROJECTIDCARD 
ADD (VERSION NUMBER);

UPDATE TABV_PROJECTIDCARD
	set VERSION = 1
	;

ALTER TABLE TABV_PROJECTIDCARD  
MODIFY (VERSION NOT NULL);

ALTER TABLE TABV_PROJECTIDCARD
 drop constraint TABV_PROJECTIDCARD_UNI
;

ALTER TABLE TABV_PROJECTIDCARD
 add constraint UK_APIC_PIDC_NAME unique(VALUE_ID) 
; 

--
-- TABV_VARIANTS_ATTR
--
-- add CRE/MOD columns
-- add VERSION column
--
ALTER TABLE TABV_VARIANTS_ATTR 
ADD (VERSION NUMBER);

ALTER TABLE TABV_VARIANTS_ATTR 
ADD (CREATED_USER VARCHAR2(30));

ALTER TABLE TABV_VARIANTS_ATTR 
ADD (CREATED_DATE TIMESTAMP);

UPDATE TABV_VARIANTS_ATTR
	set CREATED_DATE = sysdate,
	    CREATED_USER = user,
		VERSION = 1
	;

ALTER TABLE TABV_VARIANTS_ATTR  
MODIFY (VERSION NOT NULL);

ALTER TABLE TABV_VARIANTS_ATTR  
MODIFY (CREATED_USER NOT NULL);

ALTER TABLE TABV_VARIANTS_ATTR  
MODIFY (CREATED_DATE NOT NULL);

ALTER TABLE TABV_VARIANTS_ATTR 
ADD (MODIFIED_DATE TIMESTAMP);

ALTER TABLE TABV_VARIANTS_ATTR 
ADD (MODIFIED_USER VARCHAR2(30));

update tabv_variants_attr
  set used = 'Y'
where value_id is not null
  and used <> 'Y'
;

ALTER TABLE TABV_VARIANTS_ATTR 
ADD (IS_SUBVARIANT VARCHAR2(1) )
;

update tabv_variants_attr
  set is_subvariant = 'N'
;

ALTER TABLE TABV_VARIANTS_ATTR  
MODIFY (IS_SUBVARIANT NOT NULL)
;

spool off
