spool c:\temp\synonyms.log

--------------------------------------------------------
--  January-17-2014
--------------------------------------------------------

-- ICDM-518
CREATE OR REPLACE SYNONYM T_RVW_RESULTS FOR DGS_ICDM.T_RVW_RESULTS;
CREATE OR REPLACE SYNONYM T_RVW_PARTICIPANTS FOR DGS_ICDM.T_RVW_PARTICIPANTS;
CREATE OR REPLACE SYNONYM T_RVW_FUNCTIONS FOR DGS_ICDM.T_RVW_FUNCTIONS;
CREATE OR REPLACE SYNONYM T_RVW_PARAMETERS FOR DGS_ICDM.T_RVW_PARAMETERS;
CREATE OR REPLACE SYNONYM T_RVW_FILES FOR DGS_ICDM.T_RVW_FILES;


--ICDM-513
CREATE OR REPLACE SYNONYM T_UNITS FOR DGS_ICDM.T_UNITS;

spool off

