spool c:\temp\01_Table_Alters.log

---------------------------------------------------------------------
--  ALM Task : 649285 - impl : Server end and DB changes for adding users to Bosch Dept/Group
---------------------------------------------------------------------

CREATE TABLE T_A2L_RESPONSIBLITY_BSHGRP_USR ( 
    A2LRESP_BSHGRP_USR_ID NUMBER NOT NULL, 
    A2L_RESP_ID NUMBER NOT NULL, 
    USER_ID NUMBER NOT NULL, 
    CREATED_DATE TIMESTAMP NOT NULL, 
    CREATED_USER VARCHAR2(20 BYTE) NOT NULL, 
    MODIFIED_DATE TIMESTAMP, 
    MODIFIED_USER VARCHAR2(20 BYTE), 
    VERSION NUMBER NOT NULL);
    
ALTER TABLE T_A2L_RESPONSIBLITY_BSHGRP_USR ADD CONSTRAINT T_A2L_RESPONSIBLITY_BSHGRP_PK PRIMARY KEY (A2LRESP_BSHGRP_USR_ID);
ALTER TABLE T_A2L_RESPONSIBLITY_BSHGRP_USR ADD CONSTRAINT T_A2L_RESPONSIBLITY_BSHGR_UK1 UNIQUE (A2L_RESP_ID, USER_ID);
ALTER TABLE T_A2L_RESPONSIBLITY_BSHGRP_USR ADD CONSTRAINT T_A2L_RESPONSIBLITY_BSHGR_FK1 FOREIGN KEY (A2L_RESP_ID) REFERENCES T_A2L_RESPONSIBILITY (A2L_RESP_ID) ENABLE;
ALTER TABLE T_A2L_RESPONSIBLITY_BSHGRP_USR ADD CONSTRAINT T_A2L_RESPONSIBLITY_BSHGR_FK2 FOREIGN KEY (USER_ID) REFERENCES TABV_APIC_USERS (USER_ID) ENABLE;
---------------------------------------------------------------------------    
-- ALM Task:637630  - ICC wants to mark relevant WPs for their system in iCDM.
--
-- To add a new column ICC_RELEVANT_FLAG in table T_WORKPACKAGE_DIVISION.   
----------------------------------------------------------------------------
ALTER TABLE T_WORKPACKAGE_DIVISION 
    ADD (
        ICC_RELEVANT_FLAG VARCHAR2(1) DEFAULT NULL
    );  
    

    
------------------------------------------------------------------------------------   
--  ALM TaskId : 64662: Database design for ‘Coc Workpackages’ page of PIDC Editor.
------------------------------------------------------------------------------------

-------------------------------------------------------
--Table T_PIDC_VERS_COC_WP
--------------------------------------------------------

create table T_PIDC_VERS_COC_WP
    (
        PIDC_VERS_COC_WP_ID NUMBER(15) NOT NULL,
        PIDC_VERS_ID NUMBER NOT NULL, 
        WP_DIV_ID NUMBER NOT NULL,
        USED_FLAG VARCHAR2(1 BYTE) NOT NULL,
        IS_AT_CHILD_LEVEL VARCHAR2(1 BYTE) NOT NULL,
        CREATED_DATE   TIMESTAMP (6) NOT NULL, 
        CREATED_USER   VARCHAR2(30 BYTE) NOT NULL, 
        MODIFIED_DATE  TIMESTAMP (6), 
        MODIFIED_USER  VARCHAR2(30 BYTE), 
        VERSION NUMBER NOT NULL,
        
        CONSTRAINT PIDC_VERS_COC_WP_PK PRIMARY KEY (PIDC_VERS_COC_WP_ID),
        CONSTRAINT PIDC_VERS_COC_WP_UK1 UNIQUE (PIDC_VERS_ID,WP_DIV_ID),
        CONSTRAINT PIDC_VERS_COC_WP_FK1 FOREIGN KEY (PIDC_VERS_ID)
            REFERENCES T_PIDC_VERSION (PIDC_VERS_ID),
        CONSTRAINT PIDC_VERS_COC_WP_FK2 FOREIGN KEY (WP_DIV_ID)
            REFERENCES T_WORKPACKAGE_DIVISION (WP_DIV_ID)
    );

    
CREATE INDEX PIDC_VERS_COC_WP_FK1_IDX ON T_PIDC_VERS_COC_WP(PIDC_VERS_ID);
CREATE INDEX PIDC_VERS_COC_WP_FK2_IDX ON T_PIDC_VERS_COC_WP(WP_DIV_ID);

-------------------------------------------------------
--Table T_PIDC_VARIANT_COC_WP
--------------------------------------------------------

create table T_PIDC_VARIANT_COC_WP
    (
        VAR_COC_WP_ID NUMBER(15) NOT NULL,
        VARIANT_ID NUMBER NOT NULL,
        WP_DIV_ID NUMBER NOT NULL,
        USED_FLAG VARCHAR2(1 BYTE) NOT NULL,
        IS_AT_CHILD_LEVEL VARCHAR2(1 BYTE) NOT NULL,
        CREATED_DATE   TIMESTAMP (6) NOT NULL, 
        CREATED_USER   VARCHAR2(30 BYTE) NOT NULL, 
        MODIFIED_DATE  TIMESTAMP (6), 
        MODIFIED_USER  VARCHAR2(30 BYTE),
        VERSION NUMBER NOT NULL,
        
        CONSTRAINT PIDC_VAR_COC_WP_PK PRIMARY KEY (VAR_COC_WP_ID),
        CONSTRAINT PIDC_VAR_COC_WP_UK1 UNIQUE (VARIANT_ID,WP_DIV_ID),
        CONSTRAINT PIDC_VAR_COC_WP_FK1 FOREIGN KEY (VARIANT_ID)
            REFERENCES TABV_PROJECT_VARIANTS (VARIANT_ID),
        CONSTRAINT PIDC_VAR_COC_WP_FK2 FOREIGN KEY (WP_DIV_ID)
            REFERENCES T_WORKPACKAGE_DIVISION (WP_DIV_ID)
    );

CREATE INDEX PIDC_VARIANT_COC_WP_FK1_IDX ON T_PIDC_VARIANT_COC_WP(VARIANT_ID);
CREATE INDEX PIDC_VARIANT_COC_WP_FK2_IDX ON T_PIDC_VARIANT_COC_WP(WP_DIV_ID);

-------------------------------------------------------
--Table T_PIDC_SUB_VAR_COC_WP
--------------------------------------------------------

create table T_PIDC_SUB_VAR_COC_WP
    (
        SUB_VAR_COC_WP_ID NUMBER(15) NOT NULL,
        SUB_VARIANT_ID NUMBER NOT NULL,
        WP_DIV_ID NUMBER NOT NULL,
        USED_FLAG VARCHAR2(1 BYTE) NOT NULL,
        CREATED_DATE   TIMESTAMP (6) NOT NULL, 
        CREATED_USER   VARCHAR2(30 BYTE) NOT NULL, 
        MODIFIED_DATE  TIMESTAMP (6), 
        MODIFIED_USER  VARCHAR2(30 BYTE), 
        VERSION NUMBER NOT NULL,
        
        CONSTRAINT PIDC_SUB_VAR_COC_WP_PK PRIMARY KEY (SUB_VAR_COC_WP_ID),
        CONSTRAINT PIDC_SUB_VAR_COC_WP_UK1 UNIQUE (SUB_VARIANT_ID,WP_DIV_ID),
        CONSTRAINT PIDC_SUB_VAR_COC_WP_FK1 FOREIGN KEY (SUB_VARIANT_ID)
            REFERENCES TABV_PROJECT_SUB_VARIANTS (SUB_VARIANT_ID),
        CONSTRAINT PIDC_SUB_VAR_COC_WP_FK2 FOREIGN KEY (WP_DIV_ID)
            REFERENCES T_WORKPACKAGE_DIVISION (WP_DIV_ID)
    );

CREATE INDEX PIDC_SUB_VAR_COC_WP_FK1_IDX  ON T_PIDC_SUB_VAR_COC_WP(SUB_VARIANT_ID);
CREATE INDEX PIDC_SUB_VAR_COC_WP_FK2_IDX  ON T_PIDC_SUB_VAR_COC_WP(WP_DIV_ID);

spool off