//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.04 at 03:08:31 PM IST 
//


package com.bosch.easee.eASEEcdm_Service.model.prd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bosch.easee.eASEEcdm_Service.model.prd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bosch.easee.eASEEcdm_Service.model.prd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link USER.PARAMLIST }
     * 
     */
    public USER.PARAMLIST createUSERPARAMLIST() {
        return new USER.PARAMLIST();
    }

    /**
     * Create an instance of {@link USERGROUP.PARAMLIST.PARAM }
     * 
     */
    public USERGROUP.PARAMLIST.PARAM createUSERGROUPPARAMLISTPARAM() {
        return new USERGROUP.PARAMLIST.PARAM();
    }

    /**
     * Create an instance of {@link USERGROUP.PARAMLIST }
     * 
     */
    public USERGROUP.PARAMLIST createUSERGROUPPARAMLIST() {
        return new USERGROUP.PARAMLIST();
    }

    /**
     * Create an instance of {@link USERGROUP.FUNCLIST }
     * 
     */
    public USERGROUP.FUNCLIST createUSERGROUPFUNCLIST() {
        return new USERGROUP.FUNCLIST();
    }

    /**
     * Create an instance of {@link PRD }
     * 
     */
    public PRD createPRD() {
        return new PRD();
    }

    /**
     * Create an instance of {@link USER.WPLIST }
     * 
     */
    public USER.WPLIST createUSERWPLIST() {
        return new USER.WPLIST();
    }

    /**
     * Create an instance of {@link USER.FUNCLIST.FUNC }
     * 
     */
    public USER.FUNCLIST.FUNC createUSERFUNCLISTFUNC() {
        return new USER.FUNCLIST.FUNC();
    }

    /**
     * Create an instance of {@link USER.PARAMLIST.PARAM }
     * 
     */
    public USER.PARAMLIST.PARAM createUSERPARAMLISTPARAM() {
        return new USER.PARAMLIST.PARAM();
    }

    /**
     * Create an instance of {@link USERGROUP.FUNCLIST.FUNC }
     * 
     */
    public USERGROUP.FUNCLIST.FUNC createUSERGROUPFUNCLISTFUNC() {
        return new USERGROUP.FUNCLIST.FUNC();
    }

    /**
     * Create an instance of {@link USERGROUP.WPLIST.WP }
     * 
     */
    public USERGROUP.WPLIST.WP createUSERGROUPWPLISTWP() {
        return new USERGROUP.WPLIST.WP();
    }

    /**
     * Create an instance of {@link USER.GROUPLIST.GROUP }
     * 
     */
    public USER.GROUPLIST.GROUP createUSERGROUPLISTGROUP() {
        return new USER.GROUPLIST.GROUP();
    }

    /**
     * Create an instance of {@link USERGROUP }
     * 
     */
    public USERGROUP createUSERGROUP() {
        return new USERGROUP();
    }

    /**
     * Create an instance of {@link USER.GROUPLIST }
     * 
     */
    public USER.GROUPLIST createUSERGROUPLIST() {
        return new USER.GROUPLIST();
    }

    /**
     * Create an instance of {@link USER.WPLIST.WP }
     * 
     */
    public USER.WPLIST.WP createUSERWPLISTWP() {
        return new USER.WPLIST.WP();
    }

    /**
     * Create an instance of {@link USERGROUP.WPLIST }
     * 
     */
    public USERGROUP.WPLIST createUSERGROUPWPLIST() {
        return new USERGROUP.WPLIST();
    }

    /**
     * Create an instance of {@link USERGROUP.GROUPLIST }
     * 
     */
    public USERGROUP.GROUPLIST createUSERGROUPGROUPLIST() {
        return new USERGROUP.GROUPLIST();
    }

    /**
     * Create an instance of {@link USER }
     * 
     */
    public USER createUSER() {
        return new USER();
    }

    /**
     * Create an instance of {@link USER.FUNCLIST }
     * 
     */
    public USER.FUNCLIST createUSERFUNCLIST() {
        return new USER.FUNCLIST();
    }

    /**
     * Create an instance of {@link USERGROUP.GROUPLIST.GROUP }
     * 
     */
    public USERGROUP.GROUPLIST.GROUP createUSERGROUPGROUPLISTGROUP() {
        return new USERGROUP.GROUPLIST.GROUP();
    }

}
