//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.04 at 03:08:31 PM IST 
//


package com.bosch.easee.eASEEcdm_Service.model.prd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}USERGROUP"/>
 *         &lt;element ref="{}USER"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CDMVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FileVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "usergroupAndUSER"
})
@XmlRootElement(name = "PRD")
public class PRD {

    @XmlElements({
        @XmlElement(name = "USER", type = USER.class),
        @XmlElement(name = "USERGROUP", type = USERGROUP.class)
    })
    protected List<Object> usergroupAndUSER;
    @XmlAttribute(name = "CDMVersion")
    protected String cdmVersion;
    @XmlAttribute(name = "FileVersion")
    protected String fileVersion;

    /**
     * Gets the value of the usergroupAndUSER property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usergroupAndUSER property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUSERGROUPAndUSER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link USER }
     * {@link USERGROUP }
     * 
     * 
     */
    public List<Object> getUSERGROUPAndUSER() {
        if (usergroupAndUSER == null) {
            usergroupAndUSER = new ArrayList<Object>();
        }
        return this.usergroupAndUSER;
    }

    /**
     * Gets the value of the cdmVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDMVersion() {
        return cdmVersion;
    }

    /**
     * Sets the value of the cdmVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDMVersion(String value) {
        this.cdmVersion = value;
    }

    /**
     * Gets the value of the fileVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileVersion() {
        return fileVersion;
    }

    /**
     * Sets the value of the fileVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileVersion(String value) {
        this.fileVersion = value;
    }

}
