spool c:\temp\50_Grants.log

------------------------------------------------------------------------------------------------------------------
--Task 729577 :Allow adding groups to access rights page of PIDCs

------------------------------------------------------------------------------------------------------------------
GRANT INSERT ON "T_ACTIVE_DIRECTORY_GROUPS" TO "DGS_ICDM_JPA";

GRANT DELETE ON "T_ACTIVE_DIRECTORY_GROUPS" TO "DGS_ICDM_JPA";

GRANT SELECT ON "T_ACTIVE_DIRECTORY_GROUPS" TO "DGS_ICDM_JPA";

GRANT UPDATE ON "T_ACTIVE_DIRECTORY_GROUPS" TO "DGS_ICDM_JPA";

GRANT INSERT ON "T_ACTIVE_DIRECTORY_GROUP_NODE_ACCESS" TO "DGS_ICDM_JPA";

GRANT DELETE ON "T_ACTIVE_DIRECTORY_GROUP_NODE_ACCESS" TO "DGS_ICDM_JPA";

GRANT SELECT ON "T_ACTIVE_DIRECTORY_GROUP_NODE_ACCESS" TO "DGS_ICDM_JPA";

GRANT UPDATE ON "T_ACTIVE_DIRECTORY_GROUP_NODE_ACCESS" TO "DGS_ICDM_JPA";

GRANT INSERT ON "T_ACTIVE_DIRECTORY_GROUP_USERS" TO "DGS_ICDM_JPA";

GRANT DELETE ON "T_ACTIVE_DIRECTORY_GROUP_USERS" TO "DGS_ICDM_JPA";

GRANT SELECT ON "T_ACTIVE_DIRECTORY_GROUP_USERS" TO "DGS_ICDM_JPA";

GRANT UPDATE ON "T_ACTIVE_DIRECTORY_GROUP_USERS" TO "DGS_ICDM_JPA";

spool off
