spool c:\temp\1.pidcVersioning.log

ALTER TABLE TABV_PROJECT_SUB_VARIANTS DISABLE ALL TRIGGERS;

ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR DISABLE ALL TRIGGERS;

ALTER TABLE TABV_PROJECT_VARIANTS DISABLE ALL TRIGGERS;

ALTER TABLE TABV_VARIANTS_ATTR DISABLE ALL TRIGGERS;

ALTER TABLE TABV_PROJECT_ATTR DISABLE ALL TRIGGERS;

ALTER TABLE T_RVW_RESULTS DISABLE ALL TRIGGERS;

ALTER TABLE TABV_PIDC_DET_STRUCTURE DISABLE ALL TRIGGERS;

ALTER TABLE TABV_PROJECTIDCARD DISABLE ALL TRIGGERS;

spool off