spool c:\temp\2.pidcVersioning.log

CREATE TABLE T_PIDC_VERSION( 
   PIDC_VERS_ID NUMBER (15),
   PROJECT_ID NUMBER (15),
   PRO_REV_ID NUMBER (15),
   PID_STATUS VARCHAR2(1),
   VERS_NAME  VARCHAR2(100),
   VERS_DESC_ENG VARCHAR2(200),
   VERS_DESC_GER VARCHAR2(200),
   PARENT_PIDC_VERS_ID NUMBER (15),
   DELETED_FLAG VARCHAR2(1),
   CREATED_DATE  TIMESTAMP(6),
   CREATED_USER  VARCHAR2(30),
   MODIFIED_DATE  TIMESTAMP(6),
   MODIFIED_USER  VARCHAR2(30),
   VERSION NUMBER,  
   
   CONSTRAINT T_PIDC_VERSION_PK PRIMARY KEY (PIDC_VERS_ID),
   CONSTRAINT T_PIDC_VERSION_FK1 FOREIGN KEY (PROJECT_ID) REFERENCES TABV_PROJECTIDCARD (PROJECT_ID),
   CONSTRAINT T_PIDC_VERSION_FK2 FOREIGN KEY (PARENT_PIDC_VERS_ID) REFERENCES T_PIDC_VERSION (PIDC_VERS_ID),
   CONSTRAINT T_PIDC_VERSION_UK1 UNIQUE (PROJECT_ID,PRO_REV_ID)
 );

COMMIT;
 
spool off