spool c:\temp\3.pidcVersioning.log

--TABV_PROJECT_SUB_VARIANTS
ALTER TABLE TABV_PROJECT_SUB_VARIANTS
ADD PIDC_VERS_ID NUMBER(15) CONSTRAINT TABV_PROJ_SUB_VAR_FK_PIDC_VER REFERENCES T_PIDC_VERSION(PIDC_VERS_ID);

--TABV_PROJ_SUB_VARIANTS_ATTR
ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR
ADD PIDC_VERS_ID NUMBER(15) CONSTRAINT TABV_SUB_VAR_ATTR_FK_PID_VER REFERENCES T_PIDC_VERSION(PIDC_VERS_ID);

--TABV_PROJECT_VARIANTS
ALTER TABLE TABV_PROJECT_VARIANTS
ADD PIDC_VERS_ID NUMBER(15) CONSTRAINT TABV_PROJ_VAR_FK_PIDC_VER REFERENCES T_PIDC_VERSION(PIDC_VERS_ID);

--TABV_VARIANTS_ATTR
ALTER TABLE TABV_VARIANTS_ATTR
ADD PIDC_VERS_ID NUMBER(15) CONSTRAINT TABV_PROJ_VAR_ATTR_FK_PIDC_VER REFERENCES T_PIDC_VERSION(PIDC_VERS_ID);

--TABV_PROJECT_ATTR
ALTER TABLE TABV_PROJECT_ATTR
ADD PIDC_VERS_ID NUMBER(15) CONSTRAINT TABV_PROJ_ATTR_FK_PIDC_VER REFERENCES T_PIDC_VERSION(PIDC_VERS_ID);

--TABV_PIDC_DET_STRUCTURE
ALTER TABLE TABV_PIDC_DET_STRUCTURE
ADD PIDC_VERS_ID NUMBER(15) CONSTRAINT TABV_PIDC_DET_STR_FK_PID_VER REFERENCES T_PIDC_VERSION(PIDC_VERS_ID);

--TABV_PROJECTIDCARD Check if this is required 
ALTER TABLE TABV_PROJECTIDCARD
ADD PIDC_VERS_ID NUMBER(15) CONSTRAINT TABV_PROJECTIDCARD_FK_PIDC_VER REFERENCES T_PIDC_VERSION(PIDC_VERS_ID);

spool off