spool c:\temp\6.pidcVersioning.log

--T_PIDC_VERSION
ALTER TABLE T_PIDC_VERSION MODIFY PROJECT_ID NUMBER(15) NOT NULL; --PROJECT_ID NOT NULL

ALTER TABLE T_PIDC_VERSION MODIFY PRO_REV_ID NUMBER(15) NOT NULL; --PRO_REV_ID NOT NULL

ALTER TABLE T_PIDC_VERSION MODIFY CREATED_DATE TIMESTAMP(6) NOT NULL; --CREATED_DATE NOT NULL

ALTER TABLE T_PIDC_VERSION MODIFY CREATED_USER VARCHAR2(30) NOT NULL; --CREATED_USER NOT NULL

ALTER TABLE T_PIDC_VERSION MODIFY VERS_NAME VARCHAR2(100) NOT NULL; --VERS_NAME NOT NULL

ALTER TABLE T_PIDC_VERSION MODIFY VERSION NUMBER NOT NULL; --VERSION NOT NULL

ALTER TABLE T_PIDC_VERSION
    ADD CONSTRAINT CHECK_STATUS CHECK (PID_STATUS IN ('I', 'L')) ;

----CHILD TABLES
----------------------------------------
--TABV_PROJECT_SUB_VARIANTS                    
ALTER TABLE TABV_PROJECT_SUB_VARIANTS MODIFY PIDC_VERS_ID NUMBER(15) NOT NULL; -- PIDC_VERS_ID NOT NULL

--TABV_PROJ_SUB_VARIANTS_ATTR                    
ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR MODIFY PIDC_VERS_ID NUMBER(15) NOT NULL; -- PIDC_VERS_ID NOT NULL

--TABV_PROJECT_VARIANTS                    
ALTER TABLE TABV_PROJECT_VARIANTS MODIFY PIDC_VERS_ID NUMBER(15) NOT NULL; -- PIDC_VERS_ID NOT NULL

--TABV_VARIANTS_ATTR                    
ALTER TABLE TABV_VARIANTS_ATTR MODIFY PIDC_VERS_ID NUMBER(15) NOT NULL; -- PIDC_VERS_ID NOT NULL

--TABV_PROJECT_ATTR                    
ALTER TABLE TABV_PROJECT_ATTR MODIFY PIDC_VERS_ID NUMBER(15) NOT NULL; -- PIDC_VERS_ID NOT NULL
                    
--TABV_PROJECTIDCARD Check if this is required  Note: null entry found for PIDCID - 769052017 in PIDC_history table and hence in T_PIDC_VERSION --table
ALTER TABLE TABV_PROJECTIDCARD MODIFY PIDC_VERS_ID NUMBER(15) NOT NULL; -- PIDC_VERS_ID NOT NULL

--TABV_PIDC_DET_STRUCTURE IMPORTANT: To be done after update of TABV_PROJECTIDCARD
ALTER TABLE TABV_PIDC_DET_STRUCTURE MODIFY PIDC_VERS_ID NUMBER(15) NOT NULL; -- PIDC_VERS_ID NOT NULL

--constraint to have unqiue version names for a pidc
ALTER TABLE T_PIDC_VERSION
    ADD CONSTRAINT T_PIDC_VERSION_UK2 UNIQUE (PROJECT_ID,VERS_NAME);


spool off
