spool c:\temp\7.pidcVersioning.log

--347017
--759199267
--759626068
--770222069
--260017
--760344267
--759136017
--768311867
--759131767
--769052017

--The above pidc id's were found in T_PIDC_CHANGE_HISTORY which were missing in TABV_PID_HISTORY and TABV_PROJECTIDCARD

--So the existing entries for the above PID id's in T_PIDC_CHANGE_HISTORY  were updated with -1 in column PIDC_VERS_ID

--PIDC ID- 769052017 is special because it was found in TABV_PROJECTIDCARD table and T_PIDC_CHANGE_HISTORY but not in TABV_PID_HISTORY table

--table_updates
ALTER TABLE T_PIDC_CHANGE_HISTORY ADD PIDC_VERS_ID NUMBER(15);

UPDATE T_PIDC_CHANGE_HISTORY pchist SET(PIDC_VERS_ID) = (select pidver.PIDC_VERS_ID from T_PIDC_VERSION pidver where pchist.PIDC_ID=pidver.PROJECT_ID and pchist.PRO_REV_ID=pidver.PRO_REV_ID);
--UPDATE T_PIDC_CHANGE_HISTORY pchist SET PIDC_VERS_ID = -1 where pchist.PIDC_VERS_ID is null;

--ALTER TABLE T_PIDC_CHANGE_HISTORY MODIFY PIDC_VERS_ID NUMBER(15) NOT NULL; -- PIDC_VERS_ID NOT NULL

ALTER TABLE T_PIDC_CHANGE_HISTORY drop column PRO_REV_ID; -- this removes the not null constraint on PRO_REV_ID column;

ALTER TABLE T_PIDC_CHANGE_HISTORY ADD PIDC_VERS_VERS NUMBER(15);

UPDATE T_PIDC_CHANGE_HISTORY pchist SET PIDC_VERS_VERS = 1 where pchist.PIDC_VERS_ID is not null;

ALTER TABLE T_PIDC_CHANGE_HISTORY ADD OLD_PIDC_A2L_ID NUMBER(15);

ALTER TABLE T_PIDC_CHANGE_HISTORY ADD NEW_PIDC_A2L_ID NUMBER(15);

--ALTER TABLE T_PIDC_CHANGE_HISTORY MODIFY PIDC_VERS_VERS NUMBER(15) NOT NULL;



--table_updates
ALTER TABLE TABV_ATTR_HISTORY ADD PIDC_VERS_ID NUMBER(15);

UPDATE TABV_ATTR_HISTORY attrhis SET(PIDC_VERS_ID)=(select pidver.PIDC_VERS_ID from T_PIDC_VERSION pidver where attrhis.PROJECT_ID IS NOT NULL and attrhis.PRO_REV_ID IS NOT NULL and attrhis.PROJECT_ID=pidver.PROJECT_ID and attrhis.PRO_REV_ID=pidver.PRO_REV_ID);

ALTER TABLE TABV_ATTR_HISTORY drop column PRO_REV_ID; 


ALTER TABLE T_PIDC_CHANGE_HISTORY ADD OLD_ACTIVE_STATUS VARCHAR2(1);

ALTER TABLE T_PIDC_CHANGE_HISTORY ADD NEW_ACTIVE_STATUS VARCHAR2(1);


commit;

spool off