spool c:\temp\8.pidcVersioning.log

--TABV_PROJECT_SUB_VARIANTS
ALTER TABLE TABV_PROJECT_SUB_VARIANTS
DROP CONSTRAINT TABV_PROJ_SUB_VAR_FK_UNI;

--DROP INDEX TABV_PROJ_SUB_VAR_FK_UNI; this was not needed while executing should check why

ALTER TABLE TABV_PROJECT_SUB_VARIANTS
ADD CONSTRAINT TABV_PROJ_SUB_VAR_FK_UNI UNIQUE (VALUE_ID,VARIANT_ID);

ALTER TABLE TABV_PROJECT_SUB_VARIANTS drop column PRO_REV_ID;
ALTER TABLE TABV_PROJECT_SUB_VARIANTS drop column PROJECT_ID; --drops the foreign key constraint on TABV_PROJECTIDCARD also

--TABV_PROJ_SUB_VARIANTS_ATTR
ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR
DROP CONSTRAINT TABV_PROJ_SV_ATTR_UNI;

DROP INDEX TABV_PROJ_SV_ATTR_UNI;

ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR
ADD CONSTRAINT TABV_PROJ_SV_ATTR_UNI UNIQUE (SUB_VARIANT_ID,ATTR_ID);

ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR drop column PRO_REV_ID;
ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR drop column PROJECT_ID; --drops the foreign key constraint on TABV_PROJECTIDCARD also

--TABV_PROJECT_VARIANTS
ALTER TABLE TABV_PROJECT_VARIANTS
DROP CONSTRAINT TABV_PROJECTIDCARD_FK_UNI;

DROP INDEX TABV_PROJECTIDCARD_FK_UNI;

ALTER TABLE TABV_PROJECT_VARIANTS
ADD CONSTRAINT TABV_PROJECTIDCARD_FK_UNI UNIQUE (PIDC_VERS_ID,VALUE_ID);

ALTER TABLE TABV_PROJECT_VARIANTS drop column PRO_REV_ID;
ALTER TABLE TABV_PROJECT_VARIANTS drop column PROJECT_ID; --drops the foreign key constraint on TABV_PROJECTIDCARD also

--TABV_VARIANTS_ATTR
ALTER TABLE TABV_VARIANTS_ATTR
DROP CONSTRAINT TABV_VARIANTS_ATTR_UNI;

DROP INDEX TABV_VARIANTS_ATTR_UNI;

ALTER TABLE TABV_VARIANTS_ATTR
ADD CONSTRAINT TABV_VARIANTS_ATTR_UNI UNIQUE (VARIANT_ID,ATTR_ID);

ALTER TABLE TABV_VARIANTS_ATTR drop column PRO_REV_ID;
ALTER TABLE TABV_VARIANTS_ATTR drop column PROJECT_ID; --drops the foreign key constraint on TABV_PROJECTIDCARD also

--TABV_PROJECT_ATTR
ALTER TABLE TABV_PROJECT_ATTR
DROP CONSTRAINT TABV_PROJECT_ATTR_UNI;

DROP INDEX TABV_PROJECT_ATTR_UNI;

ALTER TABLE TABV_PROJECT_ATTR
ADD CONSTRAINT TABV_PROJECT_ATTR_UNI UNIQUE (PIDC_VERS_ID,ATTR_ID);

ALTER TABLE TABV_PROJECT_ATTR drop column PRO_REV_ID;
ALTER TABLE TABV_PROJECT_ATTR drop column PROJECT_ID; --drops the foreign key constraint on TABV_PROJECTIDCARD also


--TABV_PIDC_DET_STRUCTURE
ALTER TABLE TABV_PIDC_DET_STRUCTURE
DROP CONSTRAINT TABV_PIDC_DET_STRUCTURE_UK1;

DROP INDEX TABV_PIDC_DET_STRUCTURE_UK1;

ALTER TABLE TABV_PIDC_DET_STRUCTURE
ADD CONSTRAINT TABV_PIDC_DET_STRUCTURE_UK1 UNIQUE (PIDC_VERS_ID,ATTR_ID);

ALTER TABLE TABV_PIDC_DET_STRUCTURE
DROP CONSTRAINT TABV_PIDC_DET_STRUCTURE_UK2;

DROP INDEX TABV_PIDC_DET_STRUCTURE_UK2;

ALTER TABLE TABV_PIDC_DET_STRUCTURE
ADD CONSTRAINT TABV_PIDC_DET_STRUCTURE_UK2 UNIQUE (PIDC_VERS_ID,PID_ATTR_LEVEL);

ALTER TABLE TABV_PIDC_DET_STRUCTURE drop column PIDC_ID; --drops the foreign key constraint on TABV_PROJECTIDCARD also

--TABV_PROJECTIDCARD 
DROP INDEX TABV_PROJECTIDCARD_UNI; --TABV_PROJECTIDCARD_UNI UNIQUE Constraint was already dropped in production but index was missed

ALTER TABLE TABV_PROJECTIDCARD drop column PIDC_VERS_ID; 

--TABV_PID_FAVORITES 
ALTER TABLE TABV_PID_FAVORITES
DROP CONSTRAINT TABV_PID_FAVORITES_UNI;

DROP INDEX TABV_PID_FAVORITES_UNI;

ALTER TABLE TABV_PID_FAVORITES
ADD CONSTRAINT TABV_PID_FAVORITES_UNI UNIQUE (PROJECT_ID,USER_ID);

ALTER TABLE TABV_PID_FAVORITES drop column PRO_REV_ID;

spool off