spool c:\temp\9.pidcVersioning.log

--------------------------------------------------------
-- T_PIDC_A2L
--
-- New table for storing a2l file of PIDC 
-- 
-- ICDM-1463
--

CREATE TABLE T_PIDC_A2L
  ( 
    PIDC_A2L_ID NUMBER(15) NOT NULL, 
    PROJECT_ID  NUMBER(15) NOT NULL, 
    PIDC_VERS_ID  NUMBER(15), 
    A2L_FILE_ID NUMBER(15) NOT NULL,
    SDOM_PVER_NAME VARCHAR2(50) NOT NULL,
    CREATED_DATE  TIMESTAMP(6) NOT NULL,
    CREATED_USER  VARCHAR2(30) NOT NULL,
    MODIFIED_DATE  TIMESTAMP(6),
    MODIFIED_USER  VARCHAR2(30),
    VERSION NUMBER,
    
    CONSTRAINT T_PIDC_A2L_PK PRIMARY KEY (PIDC_A2L_ID),
    CONSTRAINT T_PIDC_A2L_UK UNIQUE (PROJECT_ID,A2L_FILE_ID), 
    CONSTRAINT T_PIDC_A2L_FK1 FOREIGN KEY (PROJECT_ID) REFERENCES TABV_PROJECTIDCARD(PROJECT_ID),
    CONSTRAINT T_PIDC_A2L_FK2 FOREIGN KEY (PIDC_VERS_ID) REFERENCES T_PIDC_VERSION(PIDC_VERS_ID) 
   );
 
 

COMMIT;

spool off