spool c:\temp\14.pidcVersioning.log

ALTER TABLE TABV_PROJECT_SUB_VARIANTS ENABLE ALL TRIGGERS; --2 Enabled

ALTER TABLE TABV_PROJ_SUB_VARIANTS_ATTR ENABLE ALL TRIGGERS;--3 Enabled

ALTER TABLE TABV_PROJECT_VARIANTS ENABLE ALL TRIGGERS;  --3 Enabled

ALTER TABLE TABV_VARIANTS_ATTR ENABLE ALL TRIGGERS; --3 Enabled

ALTER TABLE TABV_PROJECT_ATTR ENABLE ALL TRIGGERS; --3 Enabled

ALTER TABLE T_RVW_RESULTS ENABLE ALL TRIGGERS; --2 Enabled

ALTER TABLE TABV_PIDC_DET_STRUCTURE ENABLE ALL TRIGGERS; --2 Enabled

ALTER TABLE TABV_PROJECTIDCARD ENABLE ALL TRIGGERS; --3 Enabled

ALTER TABLE T_PIDC_VERSION ENABLE ALL TRIGGERS; --Done in Create new triggers

ALTER TABLE T_PIDC_A2L ENABLE ALL TRIGGERS; --Done in Create new triggers


-----------------------------------------------------------------------------------------------------------------------------------

spool off