spool c:\temp\table_updates.log

--------------------------------------------------------
--  October-21-2013  
--------------------------------------------------------

--
-- TABV_PIDC_DET_STRUCTURE
--
-- New table for storing virtual structure of PIDC details
-- 
--

  CREATE TABLE TABV_PIDC_DET_STRUCTURE
   (PDS_ID NUMBER NOT NULL, 
    PIDC_ID NUMBER NOT NULL, 
    ATTR_ID NUMBER NOT NULL, 
    PID_ATTR_LEVEL NUMBER(2) NOT NULL, 
    CREATED_USER VARCHAR2(30) NOT NULL, 
    CREATED_DATE TIMESTAMP (6) NOT NULL, 
    MODIFIED_DATE TIMESTAMP (6), 
    MODIFIED_USER VARCHAR2(30), 
    VERSION NUMBER NOT NULL, 
    
    CONSTRAINT TABV_PIDC_DET_STRUCTURE_PK PRIMARY KEY (PDS_ID), 
    CONSTRAINT TABV_PIDC_DET_STRUCTURE_UK1 UNIQUE (PIDC_ID, ATTR_ID),
    CONSTRAINT TABV_PIDC_DET_STRUCTURE_UK2 UNIQUE (PIDC_ID, PID_ATTR_LEVEL), 
     
    CONSTRAINT TABV_PIDC_DET_STRUCTURE_FK1 FOREIGN KEY (PIDC_ID) REFERENCES TABV_PROJECTIDCARD (PROJECT_ID),
    CONSTRAINT TABV_PIDC_DET_STRUCTURE_FK2 FOREIGN KEY (ATTR_ID) REFERENCES TABV_ATTRIBUTES (ATTR_ID)
   );


spool off
