spool c:\temp\tz-migration.log

----------------------------------------------------------------------------------------------------------------------------------
-- Migration script to convert TIMESTAMP columns to TIMEZONE based TIMESTAMP columns
--
-- Activities included 
-- a) Date columns (CREATED_DATE, MODIFIED_DATE) present in some tables are converted to TIMESTAMP to make this uniform throughout
-- b) Update the current values in the above columns to their UTC equivalent time using function sys_extract_utc(). 
--    
-- Assumption : the existing time in these columns is in German Time Zone (Europe/Berlin - GMT + 2.00 hrs)
--
----------------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------
--
-- IMPORTANT : Script is to be executed in DGS_ICDM schema
--
------------------------------------------------------------------------


------------------------------------------------------------------------
-- 
-- ICDM-787 - Timezone based date in Attribute Editor tables
------------------------------------------------------------------------

ALTER SESSION SET TIME_ZONE = 'Europe/Berlin';

UPDATE TABV_ATTR_SUPER_GROUPS SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_ATTR_SUPER_GROUPS SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);

UPDATE TABV_ATTR_GROUPS SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_ATTR_GROUPS SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);

UPDATE TABV_ATTRIBUTES SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_ATTRIBUTES SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);

UPDATE TABV_ATTR_VALUES SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_ATTR_VALUES SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);

UPDATE TABV_ATTR_DEPENDENCIES SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_ATTR_DEPENDENCIES SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);

commit;

ALTER SESSION SET TIME_ZONE = local;

------------------------------------------------------------------------
-- 
-- ICDM-828 - Timezone based date in PID Cards
------------------------------------------------------------------------
ALTER TABLE T_PIDC_CHANGE_HISTORY MODIFY CHANGED_DATE TIMESTAMP(6);

ALTER SESSION SET TIME_ZONE = 'Europe/Berlin';



UPDATE T_PIDC_CHANGE_HISTORY SET CHANGED_DATE = SYS_EXTRACT_UTC(CHANGED_DATE);

UPDATE TABV_ATTR_HISTORY SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_ATTR_HISTORY SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE TABV_ATTR_HISTORY SET OPERATION_DATE = SYS_EXTRACT_UTC(OPERATION_DATE);

UPDATE TABV_PIDC_DET_STRUCTURE SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_PIDC_DET_STRUCTURE SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE TABV_PID_FAVORITES SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_PID_HISTORY SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_PROJECTIDCARD SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_PROJECTIDCARD SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE TABV_PROJECT_ATTR SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_PROJECT_ATTR SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE TABV_PROJECT_SUB_VARIANTS SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_PROJECT_SUB_VARIANTS SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE TABV_PROJECT_VARIANTS SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_PROJECT_VARIANTS SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE TABV_PROJ_SUB_VARIANTS_ATTR SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_PROJ_SUB_VARIANTS_ATTR SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);

UPDATE TABV_VARIANTS_ATTR SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_VARIANTS_ATTR SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);

commit;

ALTER SESSION SET TIME_ZONE = local;


------------------------------------------------------------------------
-- 
-- ICDM-823 - Timezone based date in use case perspective
------------------------------------------------------------------------

ALTER SESSION SET TIME_ZONE = 'Europe/Berlin';

UPDATE TABV_UCP_ATTRS SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_UCP_ATTRS SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE TABV_USE_CASES SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_USE_CASES SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE TABV_USE_CASE_GROUPS SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_USE_CASE_GROUPS SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE TABV_USE_CASE_SECTIONS SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_USE_CASE_SECTIONS SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);

commit;

ALTER SESSION SET TIME_ZONE = local;

------------------------------------------------------------------------
-- 
-- ICDM-827 - Timezone based date in CDR perspective
------------------------------------------------------------------------
ALTER SESSION SET TIME_ZONE = 'Europe/Berlin';

ALTER TABLE T_RVW_FILES MODIFY CREATED_DATE TIMESTAMP(6);
ALTER TABLE T_RVW_FILES MODIFY MODIFIED_DATE TIMESTAMP(6);
ALTER TABLE T_RVW_FUNCTIONS MODIFY CREATED_DATE TIMESTAMP(6);
ALTER TABLE T_RVW_FUNCTIONS MODIFY MODIFIED_DATE TIMESTAMP(6);
ALTER TABLE T_RVW_PARAMETERS MODIFY CREATED_DATE TIMESTAMP(6);
ALTER TABLE T_RVW_PARAMETERS MODIFY MODIFIED_DATE TIMESTAMP(6);
ALTER TABLE T_RVW_PARTICIPANTS MODIFY CREATED_DATE TIMESTAMP(6);
ALTER TABLE T_RVW_PARTICIPANTS MODIFY MODIFIED_DATE TIMESTAMP(6);
ALTER TABLE T_RVW_RESULTS MODIFY CREATED_DATE TIMESTAMP(6);
ALTER TABLE T_RVW_RESULTS MODIFY MODIFIED_DATE TIMESTAMP(6);


UPDATE T_RVW_FILES SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE T_RVW_FILES SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE T_RVW_FUNCTIONS SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE T_RVW_FUNCTIONS SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE T_RVW_PARAMETERS SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE T_RVW_PARAMETERS SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE T_RVW_PARTICIPANTS SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE T_RVW_PARTICIPANTS SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE T_RVW_RESULTS SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE T_RVW_RESULTS SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE T_FUNCTIONS SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE T_FUNCTIONS SET MODIFED_DATE = SYS_EXTRACT_UTC(MODIFED_DATE);
UPDATE T_PARAMETER SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE T_PARAMETER SET MODIFED_DATE = SYS_EXTRACT_UTC(MODIFED_DATE);

commit;

ALTER SESSION SET TIME_ZONE = local;


------------------------------------------------------------------------
-- 
-- ICDM-839 - Timezone based date in General Entities
------------------------------------------------------------------------
ALTER TABLE TABV_ICDM_FILES MODIFY CREATED_DATE TIMESTAMP(6);
ALTER TABLE TABV_ICDM_FILES MODIFY MODIFIED_DATE TIMESTAMP(6);

ALTER SESSION SET TIME_ZONE = 'Europe/Berlin';

UPDATE TABV_ICDM_FILES SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_ICDM_FILES SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE TABV_APIC_ACCESS_RIGHTS SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_APIC_ACCESS_RIGHTS SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE TABV_APIC_NODE_ACCESS SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_APIC_NODE_ACCESS SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE TABV_APIC_USERS SET CREATED_DATE = SYS_EXTRACT_UTC(CREATED_DATE);
UPDATE TABV_APIC_USERS SET MODIFIED_DATE = SYS_EXTRACT_UTC(MODIFIED_DATE);
UPDATE TABV_TOP_LEVEL_ENTITIES SET LAST_MOD_DATE = SYS_EXTRACT_UTC(LAST_MOD_DATE);

commit;

ALTER SESSION SET TIME_ZONE = local;


spool off
