spool c:\temp\synonyms.log

-- ICDM-1950  create SYNONYM in ICDM JPA
CREATE OR REPLACE SYNONYM T_QUESTIONNAIRE for DGS_ICDM.T_QUESTIONNAIRE;
CREATE OR REPLACE SYNONYM T_QUESTIONNAIRE_VERSION for DGS_ICDM.T_QUESTIONNAIRE_VERSION;
CREATE OR REPLACE SYNONYM T_QUESTION for DGS_ICDM.T_QUESTION;
CREATE OR REPLACE SYNONYM T_QUESTION_CONFIG for DGS_ICDM.T_QUESTION_CONFIG;
CREATE OR REPLACE SYNONYM T_QUESTION_DEPEN_ATTRIBUTES for DGS_ICDM.T_QUESTION_DEPEN_ATTRIBUTES;
CREATE OR REPLACE SYNONYM T_QUESTION_DEPEN_ATTR_VALUES for DGS_ICDM.T_QUESTION_DEPEN_ATTR_VALUES;

-- ICDM-1979 create SYNONYM in ICDM JPA
CREATE OR REPLACE SYNONYM T_RVW_QUESTIONNAIRE for DGS_ICDM.T_RVW_QUESTIONNAIRE;
CREATE OR REPLACE SYNONYM T_RVW_QNAIRE_ANSWER for DGS_ICDM.T_RVW_QNAIRE_ANSWER;
CREATE OR REPLACE SYNONYM T_RVW_VARIANTS for DGS_ICDM.T_RVW_VARIANTS;

spool off