CREATE MATERIALIZED VIEW MV_SDOM_PVER 
NOCACHE 
USING INDEX 
REFRESH 
START WITH TO_DATE('16-May-2014 01:00:00','DD-MON-YYYY HH24:MI:SS') NEXT SYSDATE + 1 
COMPLETE 
USING DEFAULT ROLLBACK SEGMENT 
DISABLE QUERY REWRITE AS 
select VERS_NUMMER
     , EL_NAME
     , EL_NAME_ORIG
     , VARIANTE
     , REVISION 
     , ZUSTAND
     , CREATE_DATUM
     , CREATE_USER
     , AENDER_DATUM
     , AENDER_USER
from nestor_show_version_light@SCMPRO.WORLD@HEF2FE_RO
where klasse = 'PVER'
  and zustand <> 'INBEARB'
;

CREATE INDEX MV_SDOM_PVER_NAME ON MV_SDOM_PVER (EL_NAME);

CREATE UNIQUE INDEX MV_SDOM_PVER_VERSNR ON MV_SDOM_PVER (VERS_NUMMER);

GRANT select on MV_SDOM_PVER to DGS_ICDM_JPA;

