//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.27 at 01:49:18 PM CEST 
//


package com.bosch.easee.eASEEcdm_Service.model.pvd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bosch.cdl.dbmaintenance.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bosch.cdl.dbmaintenance.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WP.PARAMLIST }
     * 
     */
    public WP.PARAMLIST createWPPARAMLIST() {
        return new WP.PARAMLIST();
    }

    /**
     * Create an instance of {@link WP.PARAMLIST.PARAM }
     * 
     */
    public WP.PARAMLIST.PARAM createWPPARAMLISTPARAM() {
        return new WP.PARAMLIST.PARAM();
    }

    /**
     * Create an instance of {@link WP.GROUPLIST }
     * 
     */
    public WP.GROUPLIST createWPGROUPLIST() {
        return new WP.GROUPLIST();
    }

    /**
     * Create an instance of {@link WP }
     * 
     */
    public WP createWP() {
        return new WP();
    }

    /**
     * Create an instance of {@link WP.FUNCLIST.FUNC }
     * 
     */
    public WP.FUNCLIST.FUNC createWPFUNCLISTFUNC() {
        return new WP.FUNCLIST.FUNC();
    }

    /**
     * Create an instance of {@link PVD }
     * 
     */
    public PVD createPVD() {
        return new PVD();
    }

    /**
     * Create an instance of {@link WP.FUNCLIST }
     * 
     */
    public WP.FUNCLIST createWPFUNCLIST() {
        return new WP.FUNCLIST();
    }

    /**
     * Create an instance of {@link WP.GROUPLIST.GROUP }
     * 
     */
    public WP.GROUPLIST.GROUP createWPGROUPLISTGROUP() {
        return new WP.GROUPLIST.GROUP();
    }

    /**
     * Create an instance of {@link WP.WPLIST }
     * 
     */
    public WP.WPLIST createWPWPLIST() {
        return new WP.WPLIST();
    }

}
