//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.27 at 01:49:18 PM CEST 
//


package com.bosch.easee.eASEEcdm_Service.model.pvd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}WP"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CDMVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FileVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "wp"
})
@XmlRootElement(name = "PVD")
public class PVD {

    @XmlElement(name = "WP")
    protected List<WP> wp;
    @XmlAttribute(name = "CDMVersion")
    protected String cdmVersion;
    @XmlAttribute(name = "FileVersion")
    protected String fileVersion;

    /**
     * Gets the value of the wp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WP }
     * 
     * 
     */
    public List<WP> getWP() {
        if (wp == null) {
            wp = new ArrayList<WP>();
        }
        return this.wp;
    }

    /**
     * Gets the value of the cdmVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDMVersion() {
        return cdmVersion;
    }

    /**
     * Sets the value of the cdmVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDMVersion(String value) {
        this.cdmVersion = value;
    }

    /**
     * Gets the value of the fileVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileVersion() {
        return fileVersion;
    }

    /**
     * Sets the value of the fileVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileVersion(String value) {
        this.fileVersion = value;
    }

}
