spool c:\temp\01_Table_Alters.log

---------------------------------------------------------------------
--  ALM TaskId : 273756: Changes in DB, BO and web service layers
--  Alter Query for T_RM_CATEGORY, T_RM_RISK_LEVEL
---------------------------------------------------------------------  
ALTER TABLE T_RM_CATEGORY ADD CATEGORY_CODE varchar2(20);
UPDATE T_RM_CATEGORY SET CATEGORY_CODE = to_char(CATEGORY_ID);
ALTER TABLE T_RM_CATEGORY ALTER COLUMN CATEGORY_CODE varchar2(20) NOT NULL;
ALTER TABLE T_RM_CATEGORY ADD CONSTRAINT T_RM_CATEGORY_CODE_UK UNIQUE (CATEGORY_CODE);


ALTER TABLE T_RM_RISK_LEVEL ADD RISK_LVL_CODE varchar2(20);
UPDATE T_RM_RISK_LEVEL SET RISK_LVL_CODE = to_char(RISK_LEVEL_ID);
ALTER TABLE T_RM_RISK_LEVEL ALTER COLUMN RISK_LVL_CODE varchar2(20) NOT NULL;
ALTER TABLE T_RM_RISK_LEVEL ADD CONSTRAINT T_RM_RISK_LEVEL_CODE_UK UNIQUE (RISK_LVL_CODE);


-------------------------------------------------------------
------ 275697 : CODEX : Emission Robustness related tables
-------------------------------------------------------------

CREATE TABLE T_EMR_CATEGORY
  (
    CAT_ID        NUMBER NOT NULL ,
    CAT_NAME      VARCHAR2 (1000) NOT NULL ,
    CREATED_DATE  TIMESTAMP NOT NULL ,
    CREATED_USER  VARCHAR2 (30 BYTE) NOT NULL ,
    MODIFIED_DATE TIMESTAMP ,
    MODIFIED_USER VARCHAR2 (30 BYTE) ,
    VERSION       NUMBER NOT NULL,
    CONSTRAINT T_EMR_CATEGORY_PK PRIMARY KEY ( CAT_ID ),
    CONSTRAINT T_EMR_CATEGORY_NAME_UK UNIQUE ( CAT_NAME )
  );


CREATE TABLE T_EMR_MEASURE_UNIT
  (
    MU_ID   NUMBER NOT NULL ,
    MEASURE_UNIT_NAME VARCHAR2 (100) NOT NULL,
    CREATED_DATE      TIMESTAMP NOT NULL ,
    CREATED_USER      VARCHAR2 (30 BYTE) NOT NULL ,
    MODIFIED_DATE     TIMESTAMP ,
    MODIFIED_USER     VARCHAR2 (30 BYTE) ,
    VERSION           NUMBER NOT NULL,
    CONSTRAINT T_EMR_MEASURE_UNIT_PK PRIMARY KEY ( MU_ID ),
    CONSTRAINT T_EMR_MEASURE_UNIT_NAME_UK UNIQUE ( MEASURE_UNIT_NAME )
  );
  
   
CREATE TABLE T_EMR_COLUMN
  (
    COL_ID         NUMBER NOT NULL ,
    COLUMN_NAME    VARCHAR2 (1000)  NOT NULL,
    NUMERIC_FLAG   VARCHAR2 (1) NOT NULL ,
    NOMALIZED_FLAG VARCHAR2 (1) NOT NULL ,
    CREATED_DATE   TIMESTAMP NOT NULL ,
    CREATED_USER   VARCHAR2 (30 BYTE) NOT NULL ,
    MODIFIED_DATE  TIMESTAMP ,
    MODIFIED_USER  VARCHAR2 (30 BYTE) ,
    VERSION        NUMBER NOT NULL,
    CONSTRAINT T_EMR_COLUMN_PK PRIMARY KEY ( COL_ID ),
    CONSTRAINT T_EMR_COLUMN_NAME_UK UNIQUE ( COLUMN_NAME )
  );


 CREATE TABLE T_EMR_COLUMN_VALUE
  (
    COL_VALUE_ID  NUMBER NOT NULL ,
    COL_VALUE     VARCHAR2 (4000)  NOT NULL,
    COL_ID        NUMBER NOT NULL ,
    CREATED_DATE  TIMESTAMP NOT NULL ,
    CREATED_USER  VARCHAR2 (30 BYTE) NOT NULL ,
    MODIFIED_DATE TIMESTAMP ,
    MODIFIED_USER VARCHAR2 (30 BYTE) ,
    VERSION       NUMBER NOT NULL,
    CONSTRAINT T_EMR_COLUMN_VALUE_PK PRIMARY KEY ( COL_VALUE_ID ),
    CONSTRAINT T_EMR_COLUMN_VALUE_COL_ID_FK FOREIGN KEY ( COL_ID ) REFERENCES T_EMR_COLUMN ( COL_ID ),
    CONSTRAINT T_EMR_COLUMN_VALUE_COL_ID_UK UNIQUE ( COL_ID , COL_VALUE ) 
  );


CREATE TABLE T_EMR_EMISSION_STANDARD
  (
    EMS_ID                 NUMBER NOT NULL ,
    EMISSION_STANDARD_NAME VARCHAR2 (1000)  NOT NULL,
    EMISSION_STANDARD_FLAG VARCHAR2 (1) ,
    TESTCASE_FLAG          VARCHAR2 (1) ,
    MEASURES_FLAG          VARCHAR2 (1) ,
    PARENT_EMS_ID          NUMBER ,
    CREATED_DATE           TIMESTAMP NOT NULL ,
    CREATED_USER           VARCHAR2 (30 BYTE) NOT NULL ,
    MODIFIED_DATE          TIMESTAMP ,
    MODIFIED_USER          VARCHAR2 (30 BYTE) ,
    VERSION                NUMBER NOT NULL,
    CONSTRAINT T_EMR_EMISSION_STD_PK PRIMARY KEY ( EMS_ID ),
    CONSTRAINT T_EMR_EMISSION_STD_NAME_UK UNIQUE ( EMISSION_STANDARD_NAME ) ,
    CONSTRAINT T_EMR_EMS_STD_PARENT_FK FOREIGN KEY ( PARENT_EMS_ID ) REFERENCES T_EMR_EMISSION_STANDARD ( EMS_ID )
  );
  
  
  CREATE TABLE T_EMR_EXCEL_MAPPING
  (
    EXCEL_MAPPING_ID NUMBER NOT NULL ,
    EMS_ID           NUMBER ,
    MU_ID            NUMBER ,
    VALUE_IN_EXCEL   VARCHAR2 (4000) NOT NULL,
    COL_ID           NUMBER ,
    COL_VALUE_ID     NUMBER ,
    CREATED_DATE     TIMESTAMP NOT NULL ,
    CREATED_USER     VARCHAR2 (30 BYTE) NOT NULL ,
    MODIFIED_DATE    TIMESTAMP ,
    MODIFIED_USER    VARCHAR2 (30 BYTE) ,
    VERSION          NUMBER,
    CONSTRAINT T_EMR_EXCEL_MAPP_PK PRIMARY KEY ( EXCEL_MAPPING_ID ) ,
    CONSTRAINT T_EMR_EXCEL_MAPP_COL_VAL_FK FOREIGN KEY ( COL_VALUE_ID ) REFERENCES T_EMR_COLUMN_VALUE ( COL_VALUE_ID ),
    CONSTRAINT T_EMR_EXCEL_MAPP_COL_FK FOREIGN KEY ( COL_ID ) REFERENCES T_EMR_COLUMN ( COL_ID ),
    CONSTRAINT T_EMR_EXCEL_MAPP_T_EMS_FK FOREIGN KEY ( EMS_ID ) REFERENCES T_EMR_EMISSION_STANDARD ( EMS_ID ),
    CONSTRAINT T_EMR_EXCEL_MAPP_T_EMU_FK FOREIGN KEY ( MU_ID ) REFERENCES T_EMR_MEASURE_UNIT ( MU_ID )
  );
  
  
CREATE TABLE T_EMR_FILE
  (
    EMR_FILE_ID               NUMBER NOT NULL ,
    DESCRIPTION                VARCHAR2 (4000) ,    
    PIDC_VERS_ID               NUMBER (15) NOT NULL ,
    ICDM_FILE_ID                    NUMBER NOT NULL ,
    IS_VARIANT                 VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL, 
    LOADED_WITHOUT_ERRORS_FLAG VARCHAR2 (1) NOT NULL ,
    DELETED_FLAG               VARCHAR2 (1) NOT NULL ,
    CREATED_DATE               TIMESTAMP NOT NULL ,
    CREATED_USER               VARCHAR2 (30 BYTE) NOT NULL ,
    MODIFIED_USER              VARCHAR2 (30 BYTE) ,
    MODIFIED_DATE              TIMESTAMP ,
    VERSION                    NUMBER NOT NULL,
    CONSTRAINT T_EMR_FILE_PK PRIMARY KEY ( EMR_FILE_ID ),
    CONSTRAINT T_EMR_FILE_PIDC_VERS_FK FOREIGN KEY ( PIDC_VERS_ID ) REFERENCES T_PIDC_VERSION ( PIDC_VERS_ID ) ,
    CONSTRAINT T_EMR_FILE_ICDM_FILES_FK FOREIGN KEY ( ICDM_FILE_ID ) REFERENCES TABV_ICDM_FILES ( FILE_ID ),
    CONSTRAINT T_EMR_FILE_VERS_FILE_UK UNIQUE ( PIDC_VERS_ID , ICDM_FILE_ID ) 
  );
  
CREATE TABLE T_EMR_UPLOAD_ERROR
  (
    ERROR_ID      NUMBER NOT NULL ,
    EMR_FILE_ID   NUMBER NOT NULL ,
    ROW_NUMBER    NUMBER ,
    ERROR_CATEGORY   VARCHAR2 (30) NOT NULL ,
    ERROR_MESSAGE    VARCHAR2 (4000) NOT NULL ,
    ERROR_DATA    VARCHAR2 (4000) ,
    CREATED_DATE  TIMESTAMP NOT NULL ,
    CREATED_USER  VARCHAR2 (30 BYTE) NOT NULL ,
    MODIFIED_DATE TIMESTAMP ,
    MODIFIED_USER VARCHAR2 (30 BYTE) ,
    VERSION       NUMBER NOT NULL,
    CONSTRAINT T_EMR_UPLOAD_ERR_PK PRIMARY KEY ( ERROR_ID ),
    CONSTRAINT T_EMR_UPLOAD_ERR_FILE_FK FOREIGN KEY ( EMR_FILE_ID ) REFERENCES T_EMR_FILE ( EMR_FILE_ID )
  );
  
  
CREATE TABLE T_EMR_PIDC_VARIANT
  (
    EMR_PV_ID     NUMBER NOT NULL ,
    VARIANT_ID    NUMBER (15) NOT NULL ,
    EMS_ID        NUMBER NOT NULL ,
    EMR_FILE_ID   NUMBER NOT NULL ,
    CREATED_DATE  TIMESTAMP NOT NULL ,
    CREATED_USER  VARCHAR2 (30 BYTE) NOT NULL ,
    MODIFIED_DATE TIMESTAMP ,
    MODIFIED_USER VARCHAR2 (30 BYTE) ,
    VERSION       NUMBER NOT NULL,
    CONSTRAINT T_EMR_PIDC_VAR_PK PRIMARY KEY ( EMR_PV_ID ),
    CONSTRAINT T_EMR_PIDC_VAR_EMS_SHT_UK UNIQUE ( VARIANT_ID , EMS_ID , EMR_FILE_ID ) ,
    CONSTRAINT T_EMR_PIDC_VAR_VARIANT_FK FOREIGN KEY ( VARIANT_ID ) REFERENCES TABV_PROJECT_VARIANTS ( VARIANT_ID ),
    CONSTRAINT T_EMR_PIDC_VAR_EMS_FK FOREIGN KEY ( EMS_ID ) REFERENCES T_EMR_EMISSION_STANDARD ( EMS_ID ),
    CONSTRAINT T_EMR_PIDC_VAR_FILE_FK FOREIGN KEY ( EMR_FILE_ID ) REFERENCES T_EMR_FILE ( EMR_FILE_ID )
  );
  
CREATE TABLE T_EMR_FILE_DATA
  (
    FILE_DATA_ID      NUMBER NOT NULL ,
    EMR_FILE_ID       NUMBER NOT NULL,
    EMS_PROCEDURE_ID  NUMBER NOT NULL ,
    CAT_ID            NUMBER NOT NULL ,
    EMS_TESTCASE_ID   NUMBER ,
    FUEL_TYPE_NUMBER  NUMBER ,
    MU_ID             NUMBER ,
    COL_ID            NUMBER NOT NULL ,
    COL_VALUE_ID      NUMBER ,
    VALUE_NUM         NUMBER ,
    VALUE_TEXT        VARCHAR2 (4000),
    CREATED_DATE      TIMESTAMP NOT NULL ,
    CREATED_USER     VARCHAR2 (30 BYTE) NOT NULL ,
    MODIFIED_DATE    TIMESTAMP ,
    MODIFIED_USER    VARCHAR2 (30 BYTE) ,
    VERSION          NUMBER NOT NULL,
    CONSTRAINT T_EMR_FILE_DATA_PK PRIMARY KEY ( FILE_DATA_ID ),
    CONSTRAINT T_EMR_DATA_COL_VALUE_FK FOREIGN KEY ( COL_VALUE_ID ) REFERENCES T_EMR_COLUMN_VALUE ( COL_VALUE_ID ),
    CONSTRAINT T_EMR_DATA_FILE_FK FOREIGN KEY ( EMR_FILE_ID ) REFERENCES T_EMR_FILE ( EMR_FILE_ID ),
    CONSTRAINT T_EMR_DATA_COLUMN_FK FOREIGN KEY ( COL_ID ) REFERENCES T_EMR_COLUMN ( COL_ID ),
    CONSTRAINT T_EMR_DATA_CATEGORY_FK FOREIGN KEY ( CAT_ID ) REFERENCES T_EMR_CATEGORY ( CAT_ID ),
    CONSTRAINT T_EMR_DATA_EMS_PROC_FK FOREIGN KEY ( EMS_PROCEDURE_ID ) REFERENCES T_EMR_EMISSION_STANDARD ( EMS_ID ),
    CONSTRAINT T_EMR_DATA_EMS_TC_FK FOREIGN KEY ( EMS_TESTCASE_ID ) REFERENCES T_EMR_EMISSION_STANDARD ( EMS_ID ),
    CONSTRAINT T_EMR_DATA_MEASURE_FK FOREIGN KEY ( MU_ID ) REFERENCES T_EMR_MEASURE_UNIT ( MU_ID )
  );
  
--------------------------------------------------------------------------------------------------------------------------
------ Task 281621 : Tables to store COMPLI Check WebService results 
--------------------------------------------------------------------------------------------------------------------------  
   
   CREATE TABLE T_COMPLI_RVW_A2L
  (   
    RESULT_ID              NUMBER NOT NULL ,
    A2L_FILE_ID            NUMBER ,
    A2L_FILE_NAME          VARCHAR2 (200),   
    WEB_FLOW_JOB_ID        VARCHAR2(50) ,
    NUM_COMPLI             NUMBER NOT NULL ,
    SDOM_PVER_NAME         VARCHAR2(50) ,
    SDOM_PVER_VARIANT      VARCHAR2 (100)  ,
    SDOM_PVER_REVISION     NUMBER ,
    TIME_USED              NUMBER NOT NULL ,
    PIDC_VERSION_ID        NUMBER  ,
    STATUS                 VARCHAR2 (1) NOT NULL ,    
    CREATED_DATE           TIMESTAMP NOT NULL ,
    CREATED_USER           VARCHAR2 (30 BYTE) NOT NULL ,
    MODIFIED_DATE          TIMESTAMP ,
    MODIFIED_USER          VARCHAR2 (30 BYTE) ,
    VERSION                NUMBER NOT NULL,
    CONSTRAINT T_COMPLI_RVW_A2L_PK PRIMARY KEY ( RESULT_ID )  ,
    CONSTRAINT T_COMPLI_RVW_A2L_FK2 FOREIGN KEY ( PIDC_VERSION_ID ) REFERENCES T_PIDC_VERSION ( PIDC_VERS_ID )   
    );
 
     
  CREATE TABLE T_COMPLI_RVW_HEX
  (
    COMPLI_RVW_HEX_ID  NUMBER NOT NULL,
    RESULT_ID          NUMBER NOT NULL ,
    INDEX_NUM          NUMBER ,
    HEX_FILE_NAME      VARCHAR2 (200) NOT NULL ,
    VARIANT_ID         NUMBER  ,
    VCDM_DST_ID        NUMBER  ,    
    COMPLI_OK          NUMBER NOT NULL ,
    CSSD_FAIL          NUMBER NOT NULL ,   
    SSD2RV_FAIL        NUMBER NOT NULL ,
    COMPLI_FAIL        NUMBER NOT NULL,       
    CREATED_DATE       TIMESTAMP NOT NULL ,
    CREATED_USER       VARCHAR2 (30 BYTE) NOT NULL ,
    MODIFIED_DATE      TIMESTAMP ,
    MODIFIED_USER      VARCHAR2 (30 BYTE) ,
    VERSION            NUMBER NOT NULL,
    CONSTRAINT T_COMPLI_RVW_HEX_PK PRIMARY KEY ( COMPLI_RVW_HEX_ID ),
    CONSTRAINT T_COMPLI_RVW_HEX_FK1 FOREIGN KEY ( RESULT_ID ) REFERENCES T_COMPLI_RVW_A2L ( RESULT_ID ), 
    CONSTRAINT T_COMPLI_RVW_HEX_FK2 FOREIGN KEY ( VARIANT_ID ) REFERENCES tabv_project_variants ( VARIANT_ID )
  );
  
----------------------------------------------------------------
--Task 274996  - Use new column LAST_CONFIRMATION_DATE to store the date in which the user confirmed that the PIDC is up to date
----------------------------------------------------------------
ALTER TABLE TABV_USE_CASES ADD LAST_CONFIRMATION_DATE TIMESTAMP;


spool off