spool c:\temp\04_273756_Update_RM_Code.log

---------------------------------------------------------------------
--  ALM TaskId : 273756: Changes in DB, BO and web service layers
--  Update Query for T_RM_CATEGORY, T_RM_RISK_LEVEL
---------------------------------------------------------------------  

UPDATE T_RM_CATEGORY SET CATEGORY_CODE = 'RB_MONETARY_PRE_SOP' WHERE CATEGORY_GER='Risiko Monetär Pre-SOP';
UPDATE T_RM_CATEGORY SET CATEGORY_CODE = 'RB_MONETARY_POST_SOP' WHERE CATEGORY_GER='Risiko Monetär Post-SOP';
UPDATE T_RM_CATEGORY SET CATEGORY_CODE = 'RB_RISK_LAW' WHERE CATEGORY_GER='Risiko Gesetz';
UPDATE T_RM_CATEGORY SET CATEGORY_CODE = 'RB_RISK_REPUTATION' WHERE CATEGORY_GER='Risiko Reputation';
UPDATE T_RM_CATEGORY SET CATEGORY_CODE = 'RB_RISK_SAFETY' WHERE CATEGORY_GER='Risiko Safety';
UPDATE T_RM_CATEGORY SET CATEGORY_CODE = 'RB_SW_100' WHERE CATEGORY_GER='100% RB-SW';
UPDATE T_RM_CATEGORY SET CATEGORY_CODE = 'RB_SW_X' WHERE CATEGORY_GER='x% RB-SWP';
UPDATE T_RM_CATEGORY SET CATEGORY_CODE = 'RB_SW_0' WHERE CATEGORY_GER='0% RB-SW';
UPDATE T_RM_CATEGORY SET CATEGORY_CODE = 'RB_INPUT_YES' WHERE CATEGORY_GER='Eingangsdaten von RB';
UPDATE T_RM_CATEGORY SET CATEGORY_CODE = 'RB_INPUT_NO' WHERE CATEGORY_GER='Eingangsdaten nicht von RB';

UPDATE T_RM_RISK_LEVEL SET RISK_LVL_CODE = 'RISK_LVL_HIGH' WHERE RISK_WEIGHT='3';
UPDATE T_RM_RISK_LEVEL SET RISK_LVL_CODE = 'RISK_LVL_MEDIUM' WHERE RISK_WEIGHT='2';
UPDATE T_RM_RISK_LEVEL SET RISK_LVL_CODE = 'RISK_LVL_LOW' WHERE RISK_WEIGHT='1';
UPDATE T_RM_RISK_LEVEL SET RISK_LVL_CODE = 'RISK_LVL_NA' WHERE RISK_WEIGHT='0';

COMMIT;

spool off