spool c:\temp\60_synonyms.log

-------------------------------------------------------------
------ 275697 : CODEX : Emission Robustness related synonyms
-------------------------------------------------------------

CREATE OR REPLACE SYNONYM T_EMR_CATEGORY FOR DGS_ICDM.T_EMR_CATEGORY;
CREATE OR REPLACE SYNONYM T_EMR_MEASURE_UNIT FOR DGS_ICDM.T_EMR_MEASURE_UNIT;
CREATE OR REPLACE SYNONYM T_EMR_COLUMN FOR DGS_ICDM.T_EMR_COLUMN;
CREATE OR REPLACE SYNONYM T_EMR_COLUMN_VALUE FOR DGS_ICDM.T_EMR_COLUMN_VALUE;
CREATE OR REPLACE SYNONYM T_EMR_EMISSION_STANDARD FOR DGS_ICDM.T_EMR_EMISSION_STANDARD;
CREATE OR REPLACE SYNONYM T_EMR_EXCEL_MAPPING FOR DGS_ICDM.T_EMR_EXCEL_MAPPING;
CREATE OR REPLACE SYNONYM T_EMR_FILE FOR DGS_ICDM.T_EMR_FILE;
CREATE OR REPLACE SYNONYM T_EMR_UPLOAD_ERROR FOR DGS_ICDM.T_EMR_UPLOAD_ERROR;
CREATE OR REPLACE SYNONYM T_EMR_PIDC_VARIANT FOR DGS_ICDM.T_EMR_PIDC_VARIANT;
CREATE OR REPLACE SYNONYM T_EMR_FILE_DATA FOR DGS_ICDM.T_EMR_FILE_DATA;

---------------------------------------------------------------------
--  ALM TaskId : 279252: Get BC info using GET_PVER_BC function
---------------------------------------------------------------------
CREATE OR REPLACE SYNONYM GTT_EASEE_ELEMENTS FOR DGS_ICDM.GTT_EASEE_ELEMENTS;
CREATE OR REPLACE SYNONYM GET_PVER_BC for DGS_ICDM.GET_PVER_BC;
--------------------------------------------------------------
------ Task 281621 : Tables to store COMPLI Check WebService results 
-------------------------------------------------------------  
CREATE OR REPLACE SYNONYM T_COMPLI_RVW_HEX FOR DGS_ICDM.T_COMPLI_RVW_HEX;
CREATE OR REPLACE SYNONYM T_COMPLI_RVW_A2L for DGS_ICDM.T_COMPLI_RVW_A2L;



spool off