spool c:\temp\01_Table_Alters.log

---------------------------------------------------------------
----ICDM-2430 - new internal column to indicate whether an attribute can be moved between pidc levels(version-variant-subvariant
---------------------------------------------------------------
ALTER TABLE tabv_attributes ADD MOVE_DOWN_YN varchar2(1) ;


---------------------------------------------------------------
----ICDM-2561 - focus matrix review Database scripts
---------------------------------------------------------------

CREATE TABLE T_FOCUS_MATRIX_VERSION
    (
        FM_VERS_ID    NUMBER NOT NULL ,
        PIDC_VERS_ID  NUMBER NOT NULL ,
        NAME          VARCHAR2 (100) ,
        REV_NUM       NUMBER NOT NULL ,
        STATUS        VARCHAR2 (1) NOT NULL ,
        REVIEWED_USER NUMBER (15) ,
        REVIEWED_DATE TIMESTAMP ,
        LINK          VARCHAR2 (1000 BYTE) ,
        REMARK        VARCHAR2 (4000 BYTE) ,
        RVW_STATUS    VARCHAR2 (1 BYTE) ,
        CREATED_USER  VARCHAR2 (30) NOT NULL ,
        CREATED_DATE  TIMESTAMP NOT NULL ,
        MODIFIED_USER VARCHAR2 (30 BYTE) ,
        MODIFIED_DATE TIMESTAMP ,
        VERSION       NUMBER NOT NULL
    );

ALTER TABLE T_FOCUS_MATRIX_VERSION ADD CONSTRAINT 
    T_FOCUS_MATRIX_VERSION_PK PRIMARY KEY ( FM_VERS_ID ) ;

ALTER TABLE T_FOCUS_MATRIX_VERSION ADD CONSTRAINT
    T_FOCUS_MATRIX_VERSION_UK1 UNIQUE ( PIDC_VERS_ID , REV_NUM ) ;

ALTER TABLE T_FOCUS_MATRIX_VERSION ADD CONSTRAINT
    T_FOCUS_MATRIX_VERSION__FK1 FOREIGN KEY ( PIDC_VERS_ID )
    REFERENCES T_PIDC_VERSION ( PIDC_VERS_ID );

ALTER TABLE T_FOCUS_MATRIX_VERSION ADD CONSTRAINT
    T_FOCUS_MATRIX_VERSION__FK2 FOREIGN KEY ( REVIEWED_USER )
    REFERENCES TABV_APIC_USERS ( USER_ID );

--Link from T_FOCUS_MATRIX_VERSION to T_FOCUS_MATRIX
ALTER TABLE T_FOCUS_MATRIX ADD FM_VERS_ID NUMBER(15);

ALTER TABLE T_FOCUS_MATRIX ADD CONSTRAINT 
    T_FOCUS_MATRIX_FK3 FOREIGN KEY( FM_VERS_ID ) REFERENCES T_FOCUS_MATRIX_VERSION ( FM_VERS_ID );

--Change unique constraint to use FM_VERS_ID instead of PIDC_VERS_ID
ALTER TABLE T_FOCUS_MATRIX DROP CONSTRAINT T_FOCUS_MATRIX_UK_01;
ALTER TABLE T_FOCUS_MATRIX ADD CONSTRAINT T_FOCUS_MATRIX_UK_01 UNIQUE (  FM_VERS_ID , USE_CASE_ID , SECTION_ID , ATTR_ID );

--Stores attribute state in PIDC version at the time of version creation
CREATE TABLE T_FOCUS_MATRIX_VERSION_ATTR 
   (    
	    FMV_ATTR_ID    NUMBER NOT NULL, 
	    FM_VERS_ID     NUMBER NOT NULL, 
	    ATTR_ID        NUMBER NOT NULL, 
	    VARIANT_ID     NUMBER, 
	    SUB_VARIANT_ID NUMBER, 
	    USED           VARCHAR2(1 BYTE) NOT NULL, 
	    VALUE_ID       NUMBER, 
	    CREATED_DATE   TIMESTAMP (6) NOT NULL, 
	    CREATED_USER   VARCHAR2(30 BYTE) NOT NULL, 
	    MODIFIED_DATE  TIMESTAMP (6), 
	    MODIFIED_USER  VARCHAR2(30 BYTE), 
	    VERSION        NUMBER NOT NULL,
	    
     CONSTRAINT T_FOCUS_MATRIX_VERSION_ATT_PK PRIMARY KEY (FMV_ATTR_ID), 
     CONSTRAINT T_FOCUS_MATRIX_VERSION_AT_UK1 UNIQUE (FM_VERS_ID, ATTR_ID, VARIANT_ID, SUB_VARIANT_ID), 
     
     CONSTRAINT T_FOCUS_MATRIX_VERSION_AT_FK1 FOREIGN KEY (FM_VERS_ID)
        REFERENCES T_FOCUS_MATRIX_VERSION (FM_VERS_ID) , 
     CONSTRAINT T_FOCUS_MATRIX_VERSION_AT_FK2 FOREIGN KEY (ATTR_ID)
        REFERENCES TABV_ATTRIBUTES (ATTR_ID) , 
     CONSTRAINT T_FOCUS_MATRIX_VERSION_AT_FK3 FOREIGN KEY (VARIANT_ID)
        REFERENCES TABV_PROJECT_VARIANTS (VARIANT_ID) , 
     CONSTRAINT T_FOCUS_MATRIX_VERSION_AT_FK4 FOREIGN KEY (SUB_VARIANT_ID)
        REFERENCES TABV_PROJECT_SUB_VARIANTS (SUB_VARIANT_ID) , 
     CONSTRAINT T_FOCUS_MATRIX_VERSION_AT_FK5 FOREIGN KEY (VALUE_ID)
        REFERENCES TABV_ATTR_VALUES (VALUE_ID) 
   );

  CREATE INDEX T_FOCUS_MATRIX_VERS_ATTR_IDX1 ON T_FOCUS_MATRIX_VERSION_ATTR (FM_VERS_ID)   ;


-------------------------------------------------------------
--Data Migration--

--Create records in T_FOCUS_MATRIX_VERSION for all pidc versions
INSERT INTO T_FOCUS_MATRIX_VERSION (FM_VERS_ID, PIDC_VERS_ID, NAME, REV_NUM, STATUS, CREATED_USER, CREATED_DATE, VERSION)
    SELECT SeqV_Attributes.nextval, PIDC_VERS_ID, 'Working Set', 0, 'W', user, sys_extract_utc(systimestamp), 1 
    FROM( SELECT PIDC_VERS_ID from T_PIDC_VERSION);
    
--Link the fm version records with focus matrix records
update t_focus_matrix fm 
 set fm.fm_vers_id 
    = (select fmver.fm_vers_id from t_focus_matrix_version fmver 
        where fm.pidc_vers_id = fmver.pidc_vers_id)

--Set FM review info from T_FOCUS_MATRIX_REVIEW(to be removed afterwards)
UPDATE T_FOCUS_MATRIX_VERSION fm_ver
 SET (REVIEWED_USER, REVIEWED_DATE, LINK, REMARK, RVW_STATUS) 
        = (SELECT fm_rvw.REVIEWED_USER, fm_rvw.REVIEWED_DATE, fm_rvw.LINK, fm_rvw.REMARK, fm_rvw.RVW_STATUS
             FROM T_FOCUS_MATRIX_REVIEW  fm_rvw
            WHERE fm_ver.PIDC_VERS_ID = fm_rvw.PIDC_VERS_ID)
 WHERE EXISTS (
    SELECT 1
      FROM T_FOCUS_MATRIX_REVIEW  fm_rvw
     WHERE fm_ver.PIDC_VERS_ID = fm_rvw.PIDC_VERS_ID);

COMMIT;
-------------------------------------------------------------

--MARK column AS NOT NULL after data migration
ALTER TABLE T_FOCUS_MATRIX MODIFY (FM_VERS_ID NOT NULL);

-------------------------------------------------------------------------------------------------------------------------------
---ICDM-2296
-------------------------------------------------------------------------------------------------------------------------------
ALTER TABLE T_GROUP_ATTR_VALIDITY ADD VALIDITY_ATTR_ID  number(15) not null;
   
ALTER TABLE  T_GROUP_ATTR_VALIDITY ADD  CONSTRAINT T_GROUP_ATTR_VALIDITY_FK3  FOREIGN KEY (VALIDITY_ATTR_ID) REFERENCES TABV_ATTRIBUTES(ATTR_ID);
 
------------------------------------------------------------------------------------------------------------------------------------


--ICDM-2296
--Rename table name T_GROUP_ATTR_VALUES to T_PREDEFINED_ATTR_VALUES

ALTER TABLE T_GROUP_ATTR_VALUES   
    RENAME TO T_PREDEFINED_ATTR_VALUES;

--ICDM-2296 
 ALTER TABLE T_PREDEFINED_ATTR_VALUES RENAME COLUMN GAVL_ID TO PRE_ATTRVL_ID;

 
 --ICDM-2296
--Rename table name T_GROUP_ATTR_VALIDITY to T_PREDEFINED_VALIDITY

ALTER TABLE T_GROUP_ATTR_VALIDITY   
    RENAME TO T_PREDEFINED_VALIDITY;

--ICDM-2296 
ALTER TABLE T_PREDEFINED_VALIDITY RENAME COLUMN GAVD_ID TO PRE_VALDTY_ID;

ALTER TABLE T_PREDEFINED_VALIDITY RENAME COLUMN GAVL_ID TO GRP_ATTR_VAL_ID;

ALTER TABLE T_PREDEFINED_VALIDITY
    DROP CONSTRAINT T_GROUP_ATTR_VALIDITY_FK1;


ALTER TABLE T_PREDEFINED_VALIDITY ADD (
  CONSTRAINT T_GROUP_ATTR_VALIDITY_FK1 
  FOREIGN KEY (GRP_ATTR_VAL_ID) 
  REFERENCES TABV_ATTR_VALUES (VALUE_ID));

-------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------
---ICDM-2600 creating tables for storing responsibility of WP or Group
-------------------------------------------------------------------------------------------------------------------------------

------ T_A2L_RESP table
CREATE TABLE T_A2L_RESP 
   (    
     A2L_RESP_ID  NUMBER NOT NULL ,
     PIDC_A2L_ID  NUMBER NOT NULL ,
     WP_TYPE_ID   NUMBER NOT NULL,
     WP_ROOT_ID   NUMBER ,
     RESP_VAR_ID  NUMBER ,
     CREATED_DATE   TIMESTAMP (6) NOT NULL, 
     CREATED_USER   VARCHAR2(30 BYTE) NOT NULL, 
     MODIFIED_DATE  TIMESTAMP (6), 
     MODIFIED_USER  VARCHAR2(30 BYTE), 
     VERSION      NUMBER NOT NULL,
      
        
     CONSTRAINT T_A2L_RESP_AT_PK PRIMARY KEY (A2L_RESP_ID), 
     CONSTRAINT T_A2L_RESP_AT_UK1 UNIQUE (PIDC_A2L_ID, WP_TYPE_ID, WP_ROOT_ID, RESP_VAR_ID), 
     
     CONSTRAINT T_A2L_RESP_AT_FK1 FOREIGN KEY (PIDC_A2L_ID)
        REFERENCES T_PIDC_A2L (PIDC_A2L_ID) 
        
   );
  
------ T_WP_RESP
CREATE TABLE T_WP_RESP
   ( 
   RESP_ID NUMBER NOT NULL ,
   RESP_NAME VARCHAR2 (100) NOT NULL,
   CREATED_DATE   TIMESTAMP (6) NOT NULL, 
   CREATED_USER   VARCHAR2(30 BYTE) NOT NULL, 
   MODIFIED_DATE  TIMESTAMP (6), 
   MODIFIED_USER  VARCHAR2(30 BYTE), 
   VERSION      NUMBER NOT NULL,   
  
   CONSTRAINT T_WP_RESP_AT_PK PRIMARY KEY (RESP_ID), 
   CONSTRAINT T_WP_RESP_AT_UK1 UNIQUE (RESP_NAME)
   
   );
  
------- T_A2L_GROUP 
CREATE TABLE T_A2L_GROUP
   ( 
   GROUP_ID NUMBER NOT NULL ,
   GRP_NAME VARCHAR2 (100) NOT NULL,
   GRP_LONG_NAME VARCHAR2(255),
   WP_ROOT_ID NUMBER,
   A2L_ID NUMBER NOT NULL,
   CREATED_DATE   TIMESTAMP (6) NOT NULL, 
   CREATED_USER   VARCHAR2(30 BYTE) NOT NULL, 
   MODIFIED_DATE  TIMESTAMP (6), 
   MODIFIED_USER  VARCHAR2(30 BYTE), 
   VERSION      NUMBER NOT NULL,   
  
   CONSTRAINT T_A2L_GROUP_AT_PK PRIMARY KEY (GROUP_ID), 
   CONSTRAINT T_A2L_GROUP_AT_UK1 UNIQUE (GRP_NAME,WP_ROOT_ID,A2L_ID), 
   
   CONSTRAINT T_A2L_GROUP_AT_FK1 FOREIGN KEY (WP_ROOT_ID)
        REFERENCES TABV_ATTR_VALUES (VALUE_ID) 
   
   );
  
   
--T_A2L_GRP_PARAM
CREATE TABLE T_A2L_GRP_PARAM
   ( 
   A2L_PARAM_ID NUMBER(15) NOT NULL,
   PARAM_ID NUMBER NOT NULL ,
   GROUP_ID NUMBER NOT NULL ,
   CREATED_DATE   TIMESTAMP (6) NOT NULL, 
   CREATED_USER   VARCHAR2(30 BYTE) NOT NULL, 
   MODIFIED_DATE  TIMESTAMP (6), 
   MODIFIED_USER  VARCHAR2(30 BYTE), 
   VERSION      NUMBER NOT NULL,   
  
    
   CONSTRAINT T_A2L_GRP_PARAM_PK PRIMARY KEY (A2L_PARAM_ID),
   CONSTRAINT T_A2L_GRP_PARAM_AT_FK1 FOREIGN KEY (PARAM_ID)
        REFERENCES T_PARAMETER (ID),
   CONSTRAINT T_A2L_GRP_PARAM_AT_FK2 FOREIGN KEY (GROUP_ID)
        REFERENCES T_A2L_GROUP (GROUP_ID)
   
   );
   
   
   --T_A2L_WP_RESP
CREATE TABLE T_A2L_WP_RESP
   (    
     A2L_WP_RESP_ID  NUMBER NOT NULL ,
     A2L_RESP_ID  NUMBER NOT NULL ,
     RESP_ID NUMBER NOT NULL,
     WP_ID NUMBER,
     A2L_GROUP_ID NUMBER,
     CREATED_DATE   TIMESTAMP (6) NOT NULL, 
     CREATED_USER   VARCHAR2(30 BYTE) NOT NULL, 
     MODIFIED_DATE  TIMESTAMP (6), 
     MODIFIED_USER  VARCHAR2(30 BYTE), 
     VERSION      NUMBER NOT NULL,
     
     CONSTRAINT T_A2L_WP_RESP_AT_PK PRIMARY KEY (A2L_WP_RESP_ID), 
     CONSTRAINT T_A2L_WP_RESP_AT_FK1 FOREIGN KEY (A2L_RESP_ID)
        REFERENCES T_A2L_RESP (A2L_RESP_ID),
     CONSTRAINT T_A2L_WP_RESP_AT_FK2 FOREIGN KEY (RESP_ID)
        REFERENCES T_WP_RESP (RESP_ID),
     CONSTRAINT T_A2L_WP_RESP_AT_FK3 FOREIGN KEY (WP_ID)
        REFERENCES T_WORKPACKAGE (WP_ID),
     CONSTRAINT T_A2L_WP_RESP_AT_FK4 FOREIGN KEY (A2L_GROUP_ID)
        REFERENCES T_A2L_GROUP (GROUP_ID)
          
   );
   
---------------------------------------------------------------
---ICDM-2613 Parent task ICDM-2468 
---Store changes in Focus matrix 
---------------------------------------------------------------

ALTER TABLE T_PIDC_CHANGE_HISTORY 
    ADD (
    FM_VERS_ID NUMBER, 
    OLD_FM_VERS_NAME VARCHAR2(100 BYTE),
    NEW_FM_VERS_NAME VARCHAR2(100 BYTE),
    FM_VERS_REV_NUM NUMBER,
    OLD_FM_VERS_STATUS VARCHAR2(1 BYTE),
    NEW_FM_VERS_STATUS VARCHAR2(1 BYTE),
    OLD_FM_VERS_REVIEWED_USER NUMBER(15,0),
    NEW_FM_VERS_REVIEWED_USER NUMBER(15,0),
	OLD_FM_VERS_REVIEWED_DATE TIMESTAMP(6),
	NEW_FM_VERS_REVIEWED_DATE TIMESTAMP(6),
	OLD_FM_VERS_LINK VARCHAR2(1000 BYTE),
	NEW_FM_VERS_LINK VARCHAR2(1000 BYTE),
	OLD_FM_VERS_RVW_STATUS VARCHAR2(1 BYTE),
	NEW_FM_VERS_RVW_STATUS VARCHAR2(1 BYTE),
	FM_VERS_VERSION NUMBER,
	
	FM_ID NUMBER(15,0),
	FM_UCPA_ID NUMBER(15,0),
	OLD_FM_COLOR_CODE VARCHAR2(3 BYTE),
	NEW_FM_COLOR_CODE VARCHAR2(3 BYTE),
	OLD_FM_COMMENTS VARCHAR2(4000 BYTE),
	NEW_FM_COMMENTS VARCHAR2(4000 BYTE),
	FM_VERSION NUMBER,
	OLD_FM_LINK VARCHAR2(1000 BYTE),
	NEW_FM_LINK VARCHAR2(1000 BYTE),
	USE_CASE_ID NUMBER,
	SECTION_ID NUMBER);

---------------------------------------------------------------
--ICDM-2604
---------------------------------------------------------------
ALTER TABLE GTT_PARAMETERS ADD GROUP_ID NUMBER;

---------------------------------------------------------------
--ICDM-2646
---------------------------------------------------------------

CREATE TABLE T_DIV_FC2WP_TYPE (
    VALUE_ID NUMBER(15,0) NOT NULL PRIMARY KEY,
    DIVISION_NAME varchar(255) NOT NULL,
    FC2WP_TYPE varchar(255)    
);



spool off