spool c:\temp\60_synonyms.log

--------------------------------------------------------
-- IMPORTANT !!! 
-- To be executed in DGS_ICDM_JPA user
--
--------------------------------------------------------


-- ICDM-2561
CREATE OR REPLACE SYNONYM T_FOCUS_MATRIX_VERSION for DGS_ICDM.T_FOCUS_MATRIX_VERSION;
CREATE OR REPLACE SYNONYM T_FOCUS_MATRIX_VERSION_ATTR for DGS_ICDM.T_FOCUS_MATRIX_VERSION_ATTR;


CREATE OR REPLACE SYNONYM T_PREDEFINED_ATTR_VALUES for DGS_ICDM.T_PREDEFINED_ATTR_VALUES;  
CREATE OR REPLACE SYNONYM T_PREDEFINED_VALIDITY for DGS_ICDM.T_PREDEFINED_VALIDITY;

--ICDM-2600
CREATE OR REPLACE SYNONYM T_A2L_RESP for DGS_ICDM.T_A2L_RESP;  
CREATE OR REPLACE SYNONYM T_WP_RESP for DGS_ICDM.T_WP_RESP;
CREATE OR REPLACE SYNONYM T_A2L_GROUP for DGS_ICDM.T_A2L_GROUP;  
CREATE OR REPLACE SYNONYM T_A2L_GRP_PARAM for DGS_ICDM.T_A2L_GRP_PARAM;
CREATE OR REPLACE SYNONYM T_A2L_WP_RESP for DGS_ICDM.T_A2L_WP_RESP;
 
---------------------------------------------------------------
----ICDM-2646
---------------------------------------------------------------
CREATE OR REPLACE SYNONYM T_DIV_FC2WP_TYPE for DGS_ICDM.T_DIV_FC2WP_TYPE;

spool off