package com.bosch.easee.eASEEcdm_ComAPI  ;

import com4j.*;

public enum ECdmStudioOptions implements ComEnum {
    CDMSTUDIO_OPT_COMPARISON_TYPE(1),
    CDMSTUDIO_OPT_COPY_DIFFERENT_UNITS(2),
    CDMSTUDIO_OPT_COPY_DTYP_LIMIT(3),
    CDMSTUDIO_OPT_COPY_EXT_LIMIT(4),
    CDMSTUDIO_OPT_COPY_READ_ONLY(5),
    CDMSTUDIO_OPT_COPY_STD_LIMIT(6),
    CDMSTUDIO_OPT_DIFFERENT_APT_NUM(7),
    CDMSTUDIO_OPT_GLOBAL_ECU_CALIBRATION_OFFSET(8),
    CDMSTUDIO_OPT_UNEQUAL_PHYS_UNITS(11),
    CDMSTUDIO_OPT_COPYPARCOMMENT_COYPOPTIONS(13),
    CDMSTUDIO_OPT_CDF20_METADATA(14),
    CDMSTUDIO_OPT_PARAMETER_ADDRESS_MODE(15),
    CDMSTUDIO_OPT_PARAMETER_ACCURACY(16),
    CDMSTUDIO_OPT_COPY_MONOTONY(17),
    CDMSTUDIO_OPT_MONOTONY_CHECK_DEFAULT(18),
    CDMSTUDIO_OPT_COPY_HOWTOCOPYFWB(19),
    ;

    private final int value;
    ECdmStudioOptions(int value) { this.value=value; }
    public int comEnumValue() { return value; }
}
