package com.bosch.easee.eASEEcdm_ComAPI;

import com4j.*;
public enum EValidationOptions implements ComEnum {
    OVERALL_COMPLETENESS(101),PCHECK_COMPLETENESS_CO_T1LEVEL(102),
    PCHECK_COMPLETENESS_CO_T2LEVEL(103),
    PCHECK_COMPLETENESS_PO_T1LEVEL(104),
    PCHECK_COMPLETENESS_PO_T2LEVEL(105),
    PCHECK_COMPLETENESS_PO_SOURCE(106),
    PCHECK_COMPLETENESS_IDST(107),
    OVERLAPPING_PARSET(108),
    PCHECK_OVERLAP_CO_T1LEVEL(109),
    PCHECK_OVERLAP_CO_T2LEVEL(110),
    PCHECK_OVERLAP_PO_T1LEVEL(111),
    PCHECK_OVERLAP_PO_T2LEVEL(112),
    PCHECK_OVERLAP_PO_SOURCE(113),
    PCHECK_OVERLAP_IDST(114),
    COMPLETENESS_OF_PARSET(115),
    COMPLETENESS_OF_PARSET_CO(116),
    COMPLETENESS_OF_PARSET_PO(117),
    PCHECK_COMPLETENESS(150),
    PCHECK_COMPLETENESS_LEVEL_0(151),
    PCHECK_COMPLETENESS_LEVEL_1(152),
    PCHECK_COMPLETENESS_LEVEL_2(153),
    PCHECK_COMPLETENESS_ERROR(154),
    PCHECK_WORKPACKAGES(160),
    PCHECK_WORKPACKAGES_CONTRIBUTIONS(161),
    PCHECK_WORKPACKAGES_OBJECTS(162),
    PCHECK_WORKPACKAGES_ERROR(163),
    PCHECK_VALUE_CHANGE(200),
    PCHECK_VALUE_CHANGE_ERROR(201),
    PCHECK_VALUE_CHANGE_PARAMS(202),
    PCHECK_VALUE_CHANGE_MODEPHYS(203),
    PCHECK_VALUE_RANGE(210),
    PCHECK_VALUE_RULES(211),
    PCHECK_DEP_CHARACTS(212),
    DST_FREEZE_HEX_CHECK(220);

    private final int value;

    EValidationOptions(int value) {
        this.value = value;
    }

    public int comEnumValue() {
        return value;
    }
}
